import { execSync } from "node:child_process";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { afterEach, beforeEach, describe, expect, it } from "vitest";

import { detectMigrationState, migrateWorkspaceToW1, promoteToWorkspace } from "../core/migrate-workspace.js";

/**
 * These tests exercise `migrate-to-w1` against on-disk fixtures shaped like
 * the legacy multi-mode layouts the command must converge:
 *
 *   Case A  workspace root with `.first-tree-workspace` marker + tree/bindings
 *   Case B  single source + sibling shared tree (promotable)
 *   Case C  single source + sibling dedicated tree (promotable, same flow)
 *   ---     already-migrated, not-applicable, malformed inputs
 *
 * The fixtures use real `git init` to make `.git/` plausible (so detection
 * and unbound-sibling checks don't trip over filesystem oddities) but no
 * commits / remotes are necessary.
 */

let tmpRoot: string;

function makeRepo(parentDir: string, name: string): string {
  const repoDir = join(parentDir, name);
  mkdirSync(repoDir, { recursive: true });
  execSync("git init --quiet", { cwd: repoDir });
  return repoDir;
}

function writeJson(filePath: string, body: unknown): void {
  mkdirSync(join(filePath, ".."), { recursive: true });
  writeFileSync(filePath, `${JSON.stringify(body, null, 2)}\n`, "utf-8");
}

function writeFile(filePath: string, body: string): void {
  mkdirSync(join(filePath, ".."), { recursive: true });
  writeFileSync(filePath, body, "utf-8");
}

const FRAMEWORK_BLOCK = `<!-- BEGIN FIRST-TREE-SOURCE-INTEGRATION -->
## First Tree integration

> Managed block — regenerated by \`first-tree\` tooling.

stuff.
<!-- END FIRST-TREE-SOURCE-INTEGRATION -->`;

function buildAgentsMd(): string {
  return `# Project AGENTS.md\n\nProject-internal instructions stay below.\n\n${FRAMEWORK_BLOCK}\n\n## Post-block content\n\nPreserved across migration.\n`;
}

beforeEach(() => {
  tmpRoot = mkdtempSync(join(tmpdir(), "ft-migrate-test-"));
});

afterEach(() => {
  rmSync(tmpRoot, { recursive: true, force: true });
});

function makeCaseAWorkspace(): {
  workspaceRoot: string;
  treeRoot: string;
  sourceRoots: string[];
} {
  const workspaceRoot = tmpRoot;
  writeFile(join(workspaceRoot, ".first-tree-workspace"), "");

  const treeRoot = makeRepo(workspaceRoot, "context");
  // Bindings: two source repos.
  writeJson(join(treeRoot, ".first-tree", "bindings", "api-1234.json"), {
    sourceName: "api",
    sourceId: "api-1234",
  });
  writeJson(join(treeRoot, ".first-tree", "bindings", "web-5678.json"), {
    sourceName: "web",
    sourceId: "web-5678",
  });
  writeJson(join(treeRoot, ".first-tree", "tree.json"), {
    schemaVersion: 1,
    treeId: "context-aaa",
    treeMode: "shared",
    treeRepoName: "context",
  });
  writeJson(join(treeRoot, ".first-tree", "bootstrap.json"), { legacy: true });
  writeFile(join(treeRoot, "source-repos.md"), "# Source repos\n\n- api\n- web\n");

  const apiRoot = makeRepo(workspaceRoot, "api");
  writeJson(join(apiRoot, ".first-tree", "source.json"), {
    bindingMode: "workspace-member",
    sourceName: "api",
    tree: { treeRepoName: "context", remoteUrl: "https://github.com/acme/context.git" },
  });
  writeFile(join(apiRoot, "AGENTS.md"), buildAgentsMd());
  writeFile(join(apiRoot, "CLAUDE.md"), buildAgentsMd());
  writeFile(join(apiRoot, "WHITEPAPER.md"), "ws-pointer");
  writeFile(join(apiRoot, ".agents", "skills", "first-tree", "SKILL.md"), "stuff");
  writeFile(join(apiRoot, ".claude", "skills", "first-tree", "SKILL.md"), "stuff");

  const webRoot = makeRepo(workspaceRoot, "web");
  writeJson(join(webRoot, ".first-tree", "source.json"), {
    bindingMode: "workspace-member",
    sourceName: "web",
    tree: { treeRepoName: "context", remoteUrl: "https://github.com/acme/context.git" },
  });
  writeFile(join(webRoot, "AGENTS.md"), buildAgentsMd());
  writeFile(join(webRoot, ".agents", "skills", "first-tree", "SKILL.md"), "stuff");

  return { workspaceRoot, treeRoot, sourceRoots: [apiRoot, webRoot] };
}

function makeCaseBLayout(): {
  parentDir: string;
  sourceRoot: string;
  treeRoot: string;
} {
  // shared-source single repo with sibling tree, NO workspace parent.
  const parentDir = tmpRoot;
  const sourceRoot = makeRepo(parentDir, "api");
  const treeRoot = makeRepo(parentDir, "context");

  writeJson(join(sourceRoot, ".first-tree", "source.json"), {
    bindingMode: "shared-source",
    sourceName: "api",
    tree: {
      treeRepoName: "context",
      localPath: "../context",
      remoteUrl: "https://github.com/acme/context.git",
    },
  });
  writeFile(join(sourceRoot, "AGENTS.md"), buildAgentsMd());
  writeFile(join(sourceRoot, ".agents", "skills", "first-tree", "SKILL.md"), "stuff");

  writeJson(join(treeRoot, ".first-tree", "bindings", "api-aaa.json"), {
    sourceName: "api",
    sourceId: "api-aaa",
  });
  writeJson(join(treeRoot, ".first-tree", "tree.json"), {
    schemaVersion: 1,
    treeId: "context-xxx",
    treeMode: "shared",
    treeRepoName: "context",
  });

  return { parentDir, sourceRoot, treeRoot };
}

describe("detectMigrationState", () => {
  it("returns 'already-migrated' when .first-tree/workspace.json is present", () => {
    writeJson(join(tmpRoot, ".first-tree", "workspace.json"), { tree: "context", sources: ["api"] });

    const detection = detectMigrationState(tmpRoot);

    expect(detection.kind).toBe("already-migrated");
  });

  it("returns 'workspace' when legacy marker + tree/bindings present", () => {
    const fixture = makeCaseAWorkspace();

    const detection = detectMigrationState(fixture.workspaceRoot);

    expect(detection.kind).toBe("workspace");
    if (detection.kind !== "workspace") {
      throw new Error("expected workspace detection");
    }
    expect(detection.workspaceRoot).toBe(fixture.workspaceRoot);
    expect(detection.treeRoot).toBe(fixture.treeRoot);
    expect(detection.sourceRoots.sort()).toEqual(fixture.sourceRoots.sort());
  });

  it("returns 'workspace' even without the marker file as long as a tree subdir has bindings", () => {
    const fixture = makeCaseAWorkspace();
    rmSync(join(fixture.workspaceRoot, ".first-tree-workspace"));

    const detection = detectMigrationState(fixture.workspaceRoot);

    expect(detection.kind).toBe("workspace");
  });

  it("returns 'promotable-source' for a shared-source single repo with sibling tree", () => {
    const fixture = makeCaseBLayout();

    const detection = detectMigrationState(fixture.sourceRoot);

    expect(detection.kind).toBe("promotable-source");
    if (detection.kind !== "promotable-source") {
      throw new Error("expected promotable-source detection");
    }
    expect(detection.sourceRoot).toBe(fixture.sourceRoot);
    expect(detection.treeRoot).toBe(fixture.treeRoot);
    expect(detection.suggestedWorkspaceName).toBe("api-workspace");
  });

  it("returns 'not-applicable' when no legacy state is detected", () => {
    const detection = detectMigrationState(tmpRoot);

    expect(detection.kind).toBe("not-applicable");
  });

  it("returns 'not-applicable' when source.json points at a missing sibling tree", () => {
    const sourceRoot = makeRepo(tmpRoot, "api");
    writeJson(join(sourceRoot, ".first-tree", "source.json"), {
      tree: { localPath: "../nope" },
    });

    const detection = detectMigrationState(sourceRoot);

    expect(detection.kind).toBe("not-applicable");
  });
});

describe("migrateWorkspaceToW1 (Case A)", () => {
  it("writes the W1 manifest with tree subdir name + sorted source names", () => {
    const fixture = makeCaseAWorkspace();
    const detection = detectMigrationState(fixture.workspaceRoot);
    if (detection.kind !== "workspace") {
      throw new Error("expected workspace detection");
    }

    const result = migrateWorkspaceToW1(detection);

    expect(result.dryRun).toBe(false);
    expect(result.manifest).toEqual({ tree: "context", sources: ["api", "web"] });
    const written = JSON.parse(readFileSync(join(fixture.workspaceRoot, ".first-tree", "workspace.json"), "utf-8"));
    expect(written).toEqual({ tree: "context", sources: ["api", "web"] });
  });

  it("deletes the legacy .first-tree-workspace marker", () => {
    const fixture = makeCaseAWorkspace();
    const detection = detectMigrationState(fixture.workspaceRoot);
    if (detection.kind !== "workspace") {
      throw new Error("expected workspace detection");
    }

    migrateWorkspaceToW1(detection);

    expect(existsSync(join(fixture.workspaceRoot, ".first-tree-workspace"))).toBe(false);
  });

  it("strips bindings/, bootstrap.json, tree.json, source-repos.md from the tree repo", () => {
    const fixture = makeCaseAWorkspace();
    const detection = detectMigrationState(fixture.workspaceRoot);
    if (detection.kind !== "workspace") {
      throw new Error("expected workspace detection");
    }

    migrateWorkspaceToW1(detection);

    expect(existsSync(join(fixture.treeRoot, ".first-tree", "bindings"))).toBe(false);
    expect(existsSync(join(fixture.treeRoot, ".first-tree", "bootstrap.json"))).toBe(false);
    expect(existsSync(join(fixture.treeRoot, ".first-tree", "tree.json"))).toBe(false);
    expect(existsSync(join(fixture.treeRoot, "source-repos.md"))).toBe(false);
  });

  it("strips source.json, skills, WHITEPAPER from each source repo, and the framework block from AGENTS/CLAUDE", () => {
    const fixture = makeCaseAWorkspace();
    const detection = detectMigrationState(fixture.workspaceRoot);
    if (detection.kind !== "workspace") {
      throw new Error("expected workspace detection");
    }

    migrateWorkspaceToW1(detection);

    for (const sourceRoot of fixture.sourceRoots) {
      expect(existsSync(join(sourceRoot, ".first-tree", "source.json"))).toBe(false);
      expect(existsSync(join(sourceRoot, ".agents", "skills"))).toBe(false);
      expect(existsSync(join(sourceRoot, ".claude", "skills"))).toBe(false);
      expect(existsSync(join(sourceRoot, "WHITEPAPER.md"))).toBe(false);

      const agents = readFileSync(join(sourceRoot, "AGENTS.md"), "utf-8");
      expect(agents).not.toContain("BEGIN FIRST-TREE-SOURCE-INTEGRATION");
      expect(agents).toContain("# Project AGENTS.md");
      expect(agents).toContain("## Post-block content");
    }
  });

  it("dry-run reports planned changes without touching disk", () => {
    const fixture = makeCaseAWorkspace();
    const detection = detectMigrationState(fixture.workspaceRoot);
    if (detection.kind !== "workspace") {
      throw new Error("expected workspace detection");
    }

    const result = migrateWorkspaceToW1(detection, { dryRun: true });

    expect(result.dryRun).toBe(true);
    expect(result.removed.length).toBeGreaterThan(0);
    expect(existsSync(join(fixture.workspaceRoot, ".first-tree", "workspace.json"))).toBe(false);
    expect(existsSync(join(fixture.workspaceRoot, ".first-tree-workspace"))).toBe(true);
    expect(existsSync(join(fixture.treeRoot, ".first-tree", "bindings"))).toBe(true);
    for (const sourceRoot of fixture.sourceRoots) {
      expect(existsSync(join(sourceRoot, ".first-tree", "source.json"))).toBe(true);
    }
  });

  it("idempotency: after a successful migration, the workspace re-detects as already-migrated", () => {
    const fixture = makeCaseAWorkspace();
    const detection = detectMigrationState(fixture.workspaceRoot);
    if (detection.kind !== "workspace") {
      throw new Error("expected workspace detection");
    }

    migrateWorkspaceToW1(detection);

    const redetection = detectMigrationState(fixture.workspaceRoot);
    expect(redetection.kind).toBe("already-migrated");
  });

  it("does not list a source twice if both bindings/ and filesystem fallback find it", () => {
    // Build a tree with a binding pointing to "api", and an "api" subdir at
    // the workspace root that also has a stale `source.json`. Both detection
    // paths would yield "api"; the migration should only list it once.
    const fixture = makeCaseAWorkspace();
    // Remove the web sibling so only api remains.
    rmSync(join(fixture.workspaceRoot, "web"), { recursive: true, force: true });
    rmSync(join(fixture.treeRoot, ".first-tree", "bindings", "web-5678.json"));

    const detection = detectMigrationState(fixture.workspaceRoot);
    if (detection.kind !== "workspace") {
      throw new Error("expected workspace detection");
    }

    const result = migrateWorkspaceToW1(detection);

    expect(result.manifest.sources).toEqual(["api"]);
  });
});

describe("promoteToWorkspace (Case B/C)", () => {
  it("creates the workspace root and moves both repos into it", () => {
    const fixture = makeCaseBLayout();
    const detection = detectMigrationState(fixture.sourceRoot);
    if (detection.kind !== "promotable-source") {
      throw new Error("expected promotable-source detection");
    }

    const promote = promoteToWorkspace(detection);

    expect(existsSync(promote.workspaceRoot)).toBe(true);
    expect(existsSync(promote.newSourceRoot)).toBe(true);
    expect(existsSync(promote.newTreeRoot)).toBe(true);
    expect(existsSync(fixture.sourceRoot)).toBe(false);
    expect(existsSync(fixture.treeRoot)).toBe(false);
    expect(existsSync(join(promote.newSourceRoot, ".git"))).toBe(true);
    expect(existsSync(join(promote.newTreeRoot, ".git"))).toBe(true);
  });

  it("dry-run returns the planned paths without moving anything", () => {
    const fixture = makeCaseBLayout();
    const detection = detectMigrationState(fixture.sourceRoot);
    if (detection.kind !== "promotable-source") {
      throw new Error("expected promotable-source detection");
    }

    const plan = promoteToWorkspace(detection, { dryRun: true });

    expect(plan.dryRun).toBe(true);
    expect(existsSync(fixture.sourceRoot)).toBe(true);
    expect(existsSync(fixture.treeRoot)).toBe(true);
    expect(existsSync(plan.workspaceRoot)).toBe(false);
  });

  it("refuses to promote when the target workspace dir already exists", () => {
    const fixture = makeCaseBLayout();
    const detection = detectMigrationState(fixture.sourceRoot);
    if (detection.kind !== "promotable-source") {
      throw new Error("expected promotable-source detection");
    }
    // Pre-create the would-be workspace dir.
    mkdirSync(join(fixture.parentDir, detection.suggestedWorkspaceName));

    expect(() => promoteToWorkspace(detection)).toThrow(/already exists/u);
  });

  it("rejects workspace names containing path separators", () => {
    const fixture = makeCaseBLayout();
    const detection = detectMigrationState(fixture.sourceRoot);
    if (detection.kind !== "promotable-source") {
      throw new Error("expected promotable-source detection");
    }

    expect(() => promoteToWorkspace(detection, { workspaceName: "evil/path" })).toThrow(/Invalid/u);
  });

  it("end-to-end: promote then migrate yields a valid W1 workspace", () => {
    const fixture = makeCaseBLayout();
    const detection = detectMigrationState(fixture.sourceRoot);
    if (detection.kind !== "promotable-source") {
      throw new Error("expected promotable-source detection");
    }

    const promote = promoteToWorkspace(detection);
    const cleanup = migrateWorkspaceToW1(
      {
        kind: "workspace",
        workspaceRoot: promote.workspaceRoot,
        treeRoot: promote.newTreeRoot,
        sourceRoots: [promote.newSourceRoot],
      },
      {},
    );

    expect(cleanup.manifest).toEqual({ tree: "context", sources: ["api"] });
    expect(existsSync(join(promote.workspaceRoot, ".first-tree", "workspace.json"))).toBe(true);
    expect(existsSync(join(promote.newSourceRoot, ".first-tree", "source.json"))).toBe(false);
    expect(existsSync(join(promote.newTreeRoot, ".first-tree", "bindings"))).toBe(false);
  });
});
