import { execSync } from "node:child_process";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { afterEach, beforeEach, describe, expect, it } from "vitest";

import {
  detectMigrationState,
  migrateWorkspaceToW1,
  planPromotableDryRun,
  promoteToWorkspace,
} from "../core/migrate-workspace.js";

/**
 * These tests exercise `migrate-to-w1` against on-disk fixtures shaped like
 * the legacy multi-mode layouts the command must converge:
 *
 *   Case A  workspace root with `.first-tree-workspace` marker + tree/bindings
 *   Case B  single source + sibling shared tree (promotable)
 *   Case C  single source + sibling dedicated tree (promotable, same flow)
 *   ---     already-migrated, not-applicable, malformed inputs
 *
 * The fixtures use real `git init` to make `.git/` plausible (so detection
 * and unbound-sibling checks don't trip over filesystem oddities) but no
 * commits / remotes are necessary.
 */

let tmpRoot: string;

function makeRepo(parentDir: string, name: string): string {
  const repoDir = join(parentDir, name);
  mkdirSync(repoDir, { recursive: true });
  execSync("git init --quiet", { cwd: repoDir });
  return repoDir;
}

function writeJson(filePath: string, body: unknown): void {
  mkdirSync(join(filePath, ".."), { recursive: true });
  writeFileSync(filePath, `${JSON.stringify(body, null, 2)}\n`, "utf-8");
}

function writeFile(filePath: string, body: string): void {
  mkdirSync(join(filePath, ".."), { recursive: true });
  writeFileSync(filePath, body, "utf-8");
}

const FRAMEWORK_BLOCK = `<!-- BEGIN FIRST-TREE-SOURCE-INTEGRATION -->
## First Tree integration

> Managed block — regenerated by \`first-tree\` tooling.

stuff.
<!-- END FIRST-TREE-SOURCE-INTEGRATION -->`;

function buildAgentsMd(): string {
  return `# Project AGENTS.md\n\nProject-internal instructions stay below.\n\n${FRAMEWORK_BLOCK}\n\n## Post-block content\n\nPreserved across migration.\n`;
}

beforeEach(() => {
  tmpRoot = mkdtempSync(join(tmpdir(), "ft-migrate-test-"));
});

afterEach(() => {
  rmSync(tmpRoot, { recursive: true, force: true });
});

function makeCaseAWorkspace(): {
  workspaceRoot: string;
  treeRoot: string;
  sourceRoots: string[];
} {
  const workspaceRoot = tmpRoot;
  writeFile(join(workspaceRoot, ".first-tree-workspace"), "");

  const treeRoot = makeRepo(workspaceRoot, "context");
  // Bindings: two source repos.
  writeJson(join(treeRoot, ".first-tree", "bindings", "api-1234.json"), {
    sourceName: "api",
    sourceId: "api-1234",
  });
  writeJson(join(treeRoot, ".first-tree", "bindings", "web-5678.json"), {
    sourceName: "web",
    sourceId: "web-5678",
  });
  writeJson(join(treeRoot, ".first-tree", "tree.json"), {
    schemaVersion: 1,
    treeId: "context-aaa",
    treeMode: "shared",
    treeRepoName: "context",
  });
  writeJson(join(treeRoot, ".first-tree", "bootstrap.json"), { legacy: true });
  writeFile(join(treeRoot, "source-repos.md"), "# Source repos\n\n- api\n- web\n");

  const apiRoot = makeRepo(workspaceRoot, "api");
  writeJson(join(apiRoot, ".first-tree", "source.json"), {
    bindingMode: "workspace-member",
    sourceName: "api",
    tree: { treeRepoName: "context", remoteUrl: "https://github.com/acme/context.git" },
  });
  writeFile(join(apiRoot, "AGENTS.md"), buildAgentsMd());
  writeFile(join(apiRoot, "CLAUDE.md"), buildAgentsMd());
  writeFile(join(apiRoot, "WHITEPAPER.md"), "ws-pointer");
  writeFile(join(apiRoot, ".agents", "skills", "first-tree", "SKILL.md"), "stuff");
  writeFile(join(apiRoot, ".claude", "skills", "first-tree", "SKILL.md"), "stuff");

  const webRoot = makeRepo(workspaceRoot, "web");
  writeJson(join(webRoot, ".first-tree", "source.json"), {
    bindingMode: "workspace-member",
    sourceName: "web",
    tree: { treeRepoName: "context", remoteUrl: "https://github.com/acme/context.git" },
  });
  writeFile(join(webRoot, "AGENTS.md"), buildAgentsMd());
  writeFile(join(webRoot, ".agents", "skills", "first-tree", "SKILL.md"), "stuff");

  return { workspaceRoot, treeRoot, sourceRoots: [apiRoot, webRoot] };
}

function makeCaseBLayout(): {
  parentDir: string;
  sourceRoot: string;
  treeRoot: string;
} {
  // shared-source single repo with sibling tree, NO workspace parent.
  const parentDir = tmpRoot;
  const sourceRoot = makeRepo(parentDir, "api");
  const treeRoot = makeRepo(parentDir, "context");

  writeJson(join(sourceRoot, ".first-tree", "source.json"), {
    bindingMode: "shared-source",
    sourceName: "api",
    tree: {
      treeRepoName: "context",
      localPath: "../context",
      remoteUrl: "https://github.com/acme/context.git",
    },
  });
  writeFile(join(sourceRoot, "AGENTS.md"), buildAgentsMd());
  writeFile(join(sourceRoot, ".agents", "skills", "first-tree", "SKILL.md"), "stuff");

  writeJson(join(treeRoot, ".first-tree", "bindings", "api-aaa.json"), {
    sourceName: "api",
    sourceId: "api-aaa",
  });
  writeJson(join(treeRoot, ".first-tree", "tree.json"), {
    schemaVersion: 1,
    treeId: "context-xxx",
    treeMode: "shared",
    treeRepoName: "context",
  });

  return { parentDir, sourceRoot, treeRoot };
}

describe("detectMigrationState", () => {
  it("returns 'already-migrated' when .first-tree/workspace.json is present", () => {
    writeJson(join(tmpRoot, ".first-tree", "workspace.json"), { tree: "context", sources: ["api"] });

    const detection = detectMigrationState(tmpRoot);

    expect(detection.kind).toBe("already-migrated");
  });

  it("returns 'workspace' when legacy marker + tree/bindings present", () => {
    const fixture = makeCaseAWorkspace();

    const detection = detectMigrationState(fixture.workspaceRoot);

    expect(detection.kind).toBe("workspace");
    if (detection.kind !== "workspace") {
      throw new Error("expected workspace detection");
    }
    expect(detection.workspaceRoot).toBe(fixture.workspaceRoot);
    expect(detection.treeRoot).toBe(fixture.treeRoot);
    expect(detection.sourceRoots.sort()).toEqual(fixture.sourceRoots.sort());
  });

  it("returns 'workspace' even without the marker file as long as a tree subdir has bindings", () => {
    const fixture = makeCaseAWorkspace();
    rmSync(join(fixture.workspaceRoot, ".first-tree-workspace"));

    const detection = detectMigrationState(fixture.workspaceRoot);

    expect(detection.kind).toBe("workspace");
  });

  it("returns 'promotable-source' for a shared-source single repo with sibling tree", () => {
    const fixture = makeCaseBLayout();

    const detection = detectMigrationState(fixture.sourceRoot);

    expect(detection.kind).toBe("promotable-source");
    if (detection.kind !== "promotable-source") {
      throw new Error("expected promotable-source detection");
    }
    expect(detection.sourceRoot).toBe(fixture.sourceRoot);
    expect(detection.treeRoot).toBe(fixture.treeRoot);
    expect(detection.suggestedWorkspaceName).toBe("api-workspace");
  });

  it("returns 'not-applicable' when no legacy state is detected", () => {
    const detection = detectMigrationState(tmpRoot);

    expect(detection.kind).toBe("not-applicable");
  });

  it("returns 'not-applicable' when cwd is a file and child scanning cannot run", () => {
    const filePath = join(tmpRoot, "not-a-directory");
    writeFile(filePath, "plain file");

    const detection = detectMigrationState(filePath);

    expect(detection.kind).toBe("not-applicable");
  });

  it("returns 'not-applicable' when a legacy marker exists without a tree", () => {
    writeFile(join(tmpRoot, ".first-tree-workspace"), "");

    const detection = detectMigrationState(tmpRoot);

    expect(detection.kind).toBe("not-applicable");
    if (detection.kind === "not-applicable") {
      expect(detection.reason).toContain("no child directory contains a tree binding");
    }
  });

  it("returns 'not-applicable' when source.json points at a missing sibling tree", () => {
    const sourceRoot = makeRepo(tmpRoot, "api");
    writeJson(join(sourceRoot, ".first-tree", "source.json"), {
      tree: { localPath: "../nope" },
    });

    const detection = detectMigrationState(sourceRoot);

    expect(detection.kind).toBe("not-applicable");
  });

  it("returns 'not-applicable' for source.json without a usable tree object", () => {
    const sourceRoot = makeRepo(tmpRoot, "api");
    writeJson(join(sourceRoot, ".first-tree", "source.json"), []);

    const arrayDetection = detectMigrationState(sourceRoot);
    expect(arrayDetection.kind).toBe("not-applicable");
    if (arrayDetection.kind === "not-applicable") {
      expect(arrayDetection.reason).toContain("could not be parsed as JSON");
    }

    writeJson(join(sourceRoot, ".first-tree", "source.json"), { tree: null });
    const nullTreeDetection = detectMigrationState(sourceRoot);
    expect(nullTreeDetection.kind).toBe("not-applicable");
    if (nullTreeDetection.kind === "not-applicable") {
      expect(nullTreeDetection.reason).toContain("no `tree` object");
    }

    writeJson(join(sourceRoot, ".first-tree", "source.json"), { tree: {} });
    const missingPathDetection = detectMigrationState(sourceRoot);
    expect(missingPathDetection.kind).toBe("not-applicable");
    if (missingPathDetection.kind === "not-applicable") {
      expect(missingPathDetection.reason).toContain("tree.localPath");
    }
  });

  it("returns 'not-applicable' when source.json points at an absolute, non-sibling tree path", () => {
    // Codex P1#2 regression: an absolute or `..`-escaping `tree.localPath`
    // would have been promoted, which would `mv` an external repo into the
    // new workspace.
    const externalTreeParent = mkdtempSync(join(tmpdir(), "ft-external-"));
    const externalTree = makeRepo(externalTreeParent, "context");
    const sourceRoot = makeRepo(tmpRoot, "api");
    writeJson(join(sourceRoot, ".first-tree", "source.json"), {
      tree: { localPath: externalTree },
    });

    const detection = detectMigrationState(sourceRoot);

    rmSync(externalTreeParent, { recursive: true, force: true });
    expect(detection.kind).toBe("not-applicable");
    if (detection.kind === "not-applicable") {
      expect(detection.reason).toMatch(/not a sibling/u);
    }
  });

  it("returns 'not-applicable' when source.json is malformed JSON (distinct from missing path)", () => {
    const sourceRoot = makeRepo(tmpRoot, "api");
    mkdirSync(join(sourceRoot, ".first-tree"), { recursive: true });
    writeFileSync(join(sourceRoot, ".first-tree", "source.json"), "{ not valid", "utf-8");

    const detection = detectMigrationState(sourceRoot);

    expect(detection.kind).toBe("not-applicable");
    if (detection.kind === "not-applicable") {
      expect(detection.reason).toMatch(/could not be parsed/u);
    }
  });

  it("returns 'not-applicable' when running inside a source whose parent already has another source sibling", () => {
    // baixiaohang regression: promoting from a workspace-member source
    // (parent has other sources) would break the parent workspace.
    const parentDir = tmpRoot;
    const otherSource = makeRepo(parentDir, "other");
    writeJson(join(otherSource, ".first-tree", "source.json"), { tree: { localPath: "../context" } });
    const sourceRoot = makeRepo(parentDir, "api");
    makeRepo(parentDir, "context"); // sibling tree, no bindings/ — to skip the workspace branch
    writeJson(join(sourceRoot, ".first-tree", "source.json"), {
      tree: { localPath: "../context" },
    });

    const detection = detectMigrationState(sourceRoot);

    expect(detection.kind).toBe("not-applicable");
    if (detection.kind === "not-applicable") {
      expect(detection.reason).toMatch(/member of a legacy workspace/u);
    }
  });

  it("returns 'not-applicable' when running inside a source whose parent has a workspace.json (resume after partial parent migration)", () => {
    const parentDir = tmpRoot;
    mkdirSync(join(parentDir, ".first-tree"), { recursive: true });
    writeJson(join(parentDir, ".first-tree", "workspace.json"), { tree: "context", sources: ["api"] });
    const sourceRoot = makeRepo(parentDir, "api");
    makeRepo(parentDir, "context");
    writeJson(join(sourceRoot, ".first-tree", "source.json"), {
      tree: { localPath: "../context" },
    });

    const detection = detectMigrationState(sourceRoot);

    expect(detection.kind).toBe("not-applicable");
  });

  it("returns 'not-applicable' when running inside a source whose parent has a .first-tree-workspace marker", () => {
    const parentDir = tmpRoot;
    writeFile(join(parentDir, ".first-tree-workspace"), "");
    const sourceRoot = makeRepo(parentDir, "api");
    makeRepo(parentDir, "context");
    writeJson(join(sourceRoot, ".first-tree", "source.json"), {
      tree: { localPath: "../context" },
    });

    // Cwd is the source repo, but the marker at the parent should make
    // detection refuse promote and point the user up.
    const detection = detectMigrationState(sourceRoot);

    expect(detection.kind).toBe("not-applicable");
  });
});

describe("detectMigrationState — bindings + filesystem union (Codex P1#1)", () => {
  it("ignores non-json, malformed, and empty binding entries while reading source names", () => {
    const workspaceRoot = tmpRoot;
    writeFile(join(workspaceRoot, ".first-tree-workspace"), "");
    const treeRoot = makeRepo(workspaceRoot, "context");
    mkdirSync(join(treeRoot, ".first-tree", "bindings", "subdir"), { recursive: true });
    writeFile(join(treeRoot, ".first-tree", "bindings", "notes.txt"), "ignored");
    writeFile(join(treeRoot, ".first-tree", "bindings", "bad.json"), "{not-json");
    writeJson(join(treeRoot, ".first-tree", "bindings", "empty.json"), { sourceName: "" });
    writeJson(join(treeRoot, ".first-tree", "bindings", "api.json"), { sourceName: "api" });
    const apiRoot = makeRepo(workspaceRoot, "api");
    writeJson(join(apiRoot, ".first-tree", "source.json"), { tree: { treeRepoName: "context" } });

    const detection = detectMigrationState(workspaceRoot);

    expect(detection.kind).toBe("workspace");
    if (detection.kind !== "workspace") {
      throw new Error("expected workspace detection");
    }
    expect(detection.sourceRoots).toEqual([apiRoot]);
  });

  it("picks up an existing source repo whose sourceName is missing from bindings", () => {
    // Regression: bindings/ has only `api`; `web/.first-tree/source.json`
    // exists but no binding references it. The fallback scan must still
    // pick web up, OR the migration silently drops it.
    const workspaceRoot = tmpRoot;
    writeFile(join(workspaceRoot, ".first-tree-workspace"), "");
    const treeRoot = makeRepo(workspaceRoot, "context");
    writeJson(join(treeRoot, ".first-tree", "bindings", "api-1.json"), { sourceName: "api" });

    const apiRoot = makeRepo(workspaceRoot, "api");
    writeJson(join(apiRoot, ".first-tree", "source.json"), { tree: { treeRepoName: "context" } });

    const webRoot = makeRepo(workspaceRoot, "web");
    writeJson(join(webRoot, ".first-tree", "source.json"), { tree: { treeRepoName: "context" } });

    const detection = detectMigrationState(workspaceRoot);

    expect(detection.kind).toBe("workspace");
    if (detection.kind !== "workspace") {
      throw new Error("expected workspace detection");
    }
    expect(detection.sourceRoots.map((r) => r.split("/").pop()).sort()).toEqual(["api", "web"]);
  });

  it("surfaces a warning when a binding declares a source that does not exist on disk", () => {
    const workspaceRoot = tmpRoot;
    writeFile(join(workspaceRoot, ".first-tree-workspace"), "");
    const treeRoot = makeRepo(workspaceRoot, "context");
    writeJson(join(treeRoot, ".first-tree", "bindings", "api-1.json"), { sourceName: "api" });
    writeJson(join(treeRoot, ".first-tree", "bindings", "ghost-2.json"), { sourceName: "ghost" });
    const apiRoot = makeRepo(workspaceRoot, "api");
    writeJson(join(apiRoot, ".first-tree", "source.json"), { tree: { treeRepoName: "context" } });

    const detection = detectMigrationState(workspaceRoot);

    expect(detection.kind).toBe("workspace");
    if (detection.kind !== "workspace") {
      throw new Error("expected workspace detection");
    }
    expect(detection.missingFromBindings).toEqual(["ghost"]);
  });
});

describe("migrateWorkspaceToW1 (Case A)", () => {
  it("writes the W1 manifest with tree subdir name + sorted source names", () => {
    const fixture = makeCaseAWorkspace();
    const detection = detectMigrationState(fixture.workspaceRoot);
    if (detection.kind !== "workspace") {
      throw new Error("expected workspace detection");
    }

    const result = migrateWorkspaceToW1(detection);

    expect(result.dryRun).toBe(false);
    expect(result.manifest).toEqual({ tree: "context", sources: ["api", "web"] });
    const written = JSON.parse(readFileSync(join(fixture.workspaceRoot, ".first-tree", "workspace.json"), "utf-8"));
    expect(written).toEqual({ tree: "context", sources: ["api", "web"] });
  });

  it("deletes the legacy .first-tree-workspace marker", () => {
    const fixture = makeCaseAWorkspace();
    const detection = detectMigrationState(fixture.workspaceRoot);
    if (detection.kind !== "workspace") {
      throw new Error("expected workspace detection");
    }

    migrateWorkspaceToW1(detection);

    expect(existsSync(join(fixture.workspaceRoot, ".first-tree-workspace"))).toBe(false);
  });

  it("strips bindings/, bootstrap.json, tree.json, source-repos.md from the tree repo", () => {
    const fixture = makeCaseAWorkspace();
    const detection = detectMigrationState(fixture.workspaceRoot);
    if (detection.kind !== "workspace") {
      throw new Error("expected workspace detection");
    }

    migrateWorkspaceToW1(detection);

    expect(existsSync(join(fixture.treeRoot, ".first-tree", "bindings"))).toBe(false);
    expect(existsSync(join(fixture.treeRoot, ".first-tree", "bootstrap.json"))).toBe(false);
    expect(existsSync(join(fixture.treeRoot, ".first-tree", "tree.json"))).toBe(false);
    expect(existsSync(join(fixture.treeRoot, "source-repos.md"))).toBe(false);
  });

  it("strips source.json, skills, WHITEPAPER from each source repo, and the framework block from AGENTS/CLAUDE", () => {
    const fixture = makeCaseAWorkspace();
    const detection = detectMigrationState(fixture.workspaceRoot);
    if (detection.kind !== "workspace") {
      throw new Error("expected workspace detection");
    }

    migrateWorkspaceToW1(detection);

    for (const sourceRoot of fixture.sourceRoots) {
      expect(existsSync(join(sourceRoot, ".first-tree", "source.json"))).toBe(false);
      expect(existsSync(join(sourceRoot, ".agents", "skills"))).toBe(false);
      expect(existsSync(join(sourceRoot, ".claude", "skills"))).toBe(false);
      expect(existsSync(join(sourceRoot, "WHITEPAPER.md"))).toBe(false);

      const agents = readFileSync(join(sourceRoot, "AGENTS.md"), "utf-8");
      expect(agents).not.toContain("BEGIN FIRST-TREE-SOURCE-INTEGRATION");
      expect(agents).toContain("# Project AGENTS.md");
      expect(agents).toContain("## Post-block content");
    }
  });

  it("dry-run reports planned changes without touching disk", () => {
    const fixture = makeCaseAWorkspace();
    const detection = detectMigrationState(fixture.workspaceRoot);
    if (detection.kind !== "workspace") {
      throw new Error("expected workspace detection");
    }

    const result = migrateWorkspaceToW1(detection, { dryRun: true });

    expect(result.dryRun).toBe(true);
    expect(result.removed.length).toBeGreaterThan(0);
    expect(existsSync(join(fixture.workspaceRoot, ".first-tree", "workspace.json"))).toBe(false);
    expect(existsSync(join(fixture.workspaceRoot, ".first-tree-workspace"))).toBe(true);
    expect(existsSync(join(fixture.treeRoot, ".first-tree", "bindings"))).toBe(true);
    for (const sourceRoot of fixture.sourceRoots) {
      expect(existsSync(join(sourceRoot, ".first-tree", "source.json"))).toBe(true);
    }
  });

  it("idempotency: after a successful migration, the workspace re-detects as already-migrated", () => {
    const fixture = makeCaseAWorkspace();
    const detection = detectMigrationState(fixture.workspaceRoot);
    if (detection.kind !== "workspace") {
      throw new Error("expected workspace detection");
    }

    migrateWorkspaceToW1(detection);

    const redetection = detectMigrationState(fixture.workspaceRoot);
    expect(redetection.kind).toBe("already-migrated");
  });

  it("surfaces detection-time warnings (missingFromBindings) in the migration result", () => {
    const workspaceRoot = tmpRoot;
    writeFile(join(workspaceRoot, ".first-tree-workspace"), "");
    const treeRoot = makeRepo(workspaceRoot, "context");
    writeJson(join(treeRoot, ".first-tree", "bindings", "api-1.json"), { sourceName: "api" });
    writeJson(join(treeRoot, ".first-tree", "bindings", "ghost-2.json"), { sourceName: "ghost" });
    const apiRoot = makeRepo(workspaceRoot, "api");
    writeJson(join(apiRoot, ".first-tree", "source.json"), { tree: { treeRepoName: "context" } });
    const detection = detectMigrationState(workspaceRoot);
    if (detection.kind !== "workspace") {
      throw new Error("expected workspace detection");
    }

    const result = migrateWorkspaceToW1(detection);

    expect(result.warnings.some((w) => w.includes("ghost"))).toBe(true);
  });

  it("writes the manifest BEFORE deleting the workspace marker (code-reviewer P2 ordering)", () => {
    // Regression: if the manifest write throws after the marker delete +
    // tree/source cleanup, a re-run can't detect anything. The new order
    // is `writeManifest -> clean source -> clean tree -> delete marker`,
    // so a failure during cleanup leaves the marker as a detection signal.
    const fixture = makeCaseAWorkspace();
    const detection = detectMigrationState(fixture.workspaceRoot);
    if (detection.kind !== "workspace") {
      throw new Error("expected workspace detection");
    }

    migrateWorkspaceToW1(detection);

    // After success: manifest is present, marker is gone.
    expect(existsSync(join(fixture.workspaceRoot, ".first-tree", "workspace.json"))).toBe(true);
    expect(existsSync(join(fixture.workspaceRoot, ".first-tree-workspace"))).toBe(false);
  });

  it("re-detects as 'workspace' (not 'already-migrated') when manifest exists alongside legacy artifacts", () => {
    // Resume scenario: a previous migrate-to-w1 wrote the manifest, then a
    // cleanup step threw partway, leaving the marker / bindings / a source
    // with source.json behind. Detection must NOT short-circuit on the
    // manifest's presence — that would silently leave legacy state forever.
    const fixture = makeCaseAWorkspace();
    // Simulate a partial-failure state: manifest is written (step 1 ran),
    // marker still present (step 4 never ran), one source already cleaned,
    // the other still has source.json.
    writeJson(join(fixture.workspaceRoot, ".first-tree", "workspace.json"), {
      tree: "context",
      sources: ["api", "web"],
    });
    rmSync(join(fixture.sourceRoots[0], ".first-tree"), { recursive: true, force: true });

    const detection = detectMigrationState(fixture.workspaceRoot);

    expect(detection.kind).toBe("workspace");
  });

  it("finishes cleanup on a resumed migration without losing already-cleaned sources", () => {
    const fixture = makeCaseAWorkspace();
    // Pre-state: manifest written, api already cleaned, web partial.
    writeJson(join(fixture.workspaceRoot, ".first-tree", "workspace.json"), {
      tree: "context",
      sources: ["api", "web"],
    });
    // Clean api's source-side artifacts to simulate it succeeded.
    rmSync(join(fixture.sourceRoots[0], ".first-tree"), { recursive: true, force: true });
    rmSync(join(fixture.sourceRoots[0], ".agents"), { recursive: true, force: true });
    rmSync(join(fixture.sourceRoots[0], ".claude"), { recursive: true, force: true });
    rmSync(join(fixture.sourceRoots[0], "WHITEPAPER.md"), { force: true });
    // Re-run.
    const detection = detectMigrationState(fixture.workspaceRoot);
    if (detection.kind !== "workspace") {
      throw new Error(`expected workspace, got ${detection.kind}`);
    }

    const result = migrateWorkspaceToW1(detection);

    // Manifest must still list api (read from old manifest, not re-derived
    // from a now-clean filesystem).
    expect(result.manifest.sources).toEqual(["api", "web"]);
    // Web cleaned this time.
    expect(existsSync(join(fixture.sourceRoots[1], ".first-tree", "source.json"))).toBe(false);
    // Marker removed.
    expect(existsSync(join(fixture.workspaceRoot, ".first-tree-workspace"))).toBe(false);
    // Re-running again is now a true no-op.
    expect(detectMigrationState(fixture.workspaceRoot).kind).toBe("already-migrated");
  });

  it("keeps manifest-listed clean sources while skipping invalid manifest entries", () => {
    const fixture = makeCaseAWorkspace();
    writeJson(join(fixture.workspaceRoot, ".first-tree", "workspace.json"), {
      tree: "context",
      sources: ["", "context", "api", "api", 42, "web"],
    });
    rmSync(join(fixture.treeRoot, ".first-tree", "bindings"), { recursive: true, force: true });
    rmSync(join(fixture.sourceRoots[0], ".first-tree"), { recursive: true, force: true });

    const detection = detectMigrationState(fixture.workspaceRoot);

    expect(detection.kind).toBe("workspace");
    if (detection.kind !== "workspace") {
      throw new Error("expected workspace detection");
    }
    expect(detection.sourceRoots.map((sourceRoot) => sourceRoot.split("/").pop()).sort()).toEqual(["api", "web"]);
  });

  it("warns and skips cleanup for source roots outside the workspace", () => {
    const fixture = makeCaseAWorkspace();
    const externalSource = makeRepo(join(tmpRoot, "outside-parent"), "external-source");
    writeJson(join(externalSource, ".first-tree", "source.json"), { tree: { treeRepoName: "context" } });

    const result = migrateWorkspaceToW1(
      {
        kind: "workspace",
        workspaceRoot: fixture.workspaceRoot,
        treeRoot: fixture.treeRoot,
        sourceRoots: [externalSource],
      },
      { dryRun: true },
    );

    expect(result.warnings).toEqual([expect.stringContaining("not an immediate child")]);
    expect(existsSync(join(externalSource, ".first-tree", "source.json"))).toBe(true);
  });

  it("reports empty source runtime directory removal during dry-run", () => {
    const workspaceRoot = tmpRoot;
    const treeRoot = makeRepo(workspaceRoot, "context");
    const sourceRoot = makeRepo(workspaceRoot, "api");
    mkdirSync(join(sourceRoot, ".first-tree"), { recursive: true });

    const result = migrateWorkspaceToW1(
      {
        kind: "workspace",
        workspaceRoot,
        treeRoot,
        sourceRoots: [sourceRoot],
      },
      { dryRun: true },
    );

    expect(result.removed).toContainEqual({ path: "api/.first-tree", kind: "source-state-dir" });
    expect(existsSync(join(sourceRoot, ".first-tree"))).toBe(true);
  });

  it("leaves a non-empty source runtime directory in place after removing source.json", () => {
    const fixture = makeCaseAWorkspace();
    writeFile(join(fixture.sourceRoots[0], ".first-tree", "keep.txt"), "keep");
    const detection = detectMigrationState(fixture.workspaceRoot);
    if (detection.kind !== "workspace") {
      throw new Error("expected workspace detection");
    }

    migrateWorkspaceToW1(detection);

    expect(existsSync(join(fixture.sourceRoots[0], ".first-tree"))).toBe(true);
    expect(existsSync(join(fixture.sourceRoots[0], ".first-tree", "keep.txt"))).toBe(true);
  });

  it("leaves framework files unchanged when the managed block is absent", () => {
    const fixture = makeCaseAWorkspace();
    writeFile(join(fixture.sourceRoots[0], "AGENTS.md"), "# Project\n\nNo managed block.\n");
    const detection = detectMigrationState(fixture.workspaceRoot);
    if (detection.kind !== "workspace") {
      throw new Error("expected workspace detection");
    }

    const result = migrateWorkspaceToW1(detection);

    expect(result.modified.some((entry) => entry.path === "api/AGENTS.md")).toBe(false);
    expect(readFileSync(join(fixture.sourceRoots[0], "AGENTS.md"), "utf8")).toBe("# Project\n\nNo managed block.\n");
  });

  it("adds a trailing newline when stripping a terminal framework block", () => {
    const fixture = makeCaseAWorkspace();
    writeFile(join(fixture.sourceRoots[0], "AGENTS.md"), `# Project\n\n${FRAMEWORK_BLOCK}`);
    const detection = detectMigrationState(fixture.workspaceRoot);
    if (detection.kind !== "workspace") {
      throw new Error("expected workspace detection");
    }

    const result = migrateWorkspaceToW1(detection);

    expect(result.modified).toContainEqual({ path: "api/AGENTS.md", kind: "source-framework-block" });
    expect(readFileSync(join(fixture.sourceRoots[0], "AGENTS.md"), "utf8")).toBe("# Project\n\n");
  });

  it("falls back to manifest.tree when bindings/ are already gone (resume case)", () => {
    const fixture = makeCaseAWorkspace();
    // Pre-state: manifest + marker + source.json survive; bindings/ already
    // cleaned in the prior run.
    writeJson(join(fixture.workspaceRoot, ".first-tree", "workspace.json"), {
      tree: "context",
      sources: ["api", "web"],
    });
    rmSync(join(fixture.treeRoot, ".first-tree", "bindings"), { recursive: true, force: true });

    const detection = detectMigrationState(fixture.workspaceRoot);

    expect(detection.kind).toBe("workspace");
    if (detection.kind !== "workspace") {
      throw new Error("expected workspace");
    }
    expect(detection.treeRoot).toBe(fixture.treeRoot);
  });

  it("does not invent a tree root from malformed resume manifests", () => {
    writeFile(join(tmpRoot, ".first-tree-workspace"), "");
    writeJson(join(tmpRoot, ".first-tree", "workspace.json"), {
      tree: 42,
      sources: ["api"],
    });

    const detection = detectMigrationState(tmpRoot);

    expect(detection.kind).toBe("not-applicable");
    if (detection.kind === "not-applicable") {
      expect(detection.reason).toContain("no child directory contains a tree binding");
    }
  });

  it("ignores malformed manifest source lists during resume detection", () => {
    const fixture = makeCaseAWorkspace();
    writeJson(join(fixture.workspaceRoot, ".first-tree", "workspace.json"), {
      tree: "context",
      sources: "api",
    });

    const detection = detectMigrationState(fixture.workspaceRoot);

    expect(detection.kind).toBe("workspace");
    if (detection.kind !== "workspace") {
      throw new Error("expected workspace detection");
    }
    expect(detection.sourceRoots.map((sourceRoot) => sourceRoot.split("/").pop()).sort()).toEqual(["api", "web"]);
  });

  it("preserves the workspace marker when manifest write fails so re-detection still finds the workspace", () => {
    // Partial-failure regression (code-reviewer P2): if writeWorkspaceManifest
    // throws, the marker must survive so `migrate-to-w1` can be safely
    // re-run after the user resolves the underlying issue.
    const fixture = makeCaseAWorkspace();
    // Block the manifest write by placing a FILE at the .first-tree path
    // so the mkdir(.first-tree, recursive:true) inside
    // writeWorkspaceManifest throws EEXIST (path is a file, not a dir).
    rmSync(join(fixture.workspaceRoot, ".first-tree"), { recursive: true, force: true });
    writeFileSync(join(fixture.workspaceRoot, ".first-tree"), "blocker", "utf-8");

    const detection = detectMigrationState(fixture.workspaceRoot);
    if (detection.kind !== "workspace") {
      throw new Error("expected workspace detection");
    }

    expect(() => migrateWorkspaceToW1(detection)).toThrow();

    // Marker survives → re-run still detects the workspace branch.
    expect(existsSync(join(fixture.workspaceRoot, ".first-tree-workspace"))).toBe(true);
    expect(existsSync(join(fixture.treeRoot, ".first-tree", "bindings"))).toBe(true);
    rmSync(join(fixture.workspaceRoot, ".first-tree"));
    const redetection = detectMigrationState(fixture.workspaceRoot);
    expect(redetection.kind).toBe("workspace");
  });

  it("does not list a source twice if both bindings/ and filesystem fallback find it", () => {
    // Build a tree with a binding pointing to "api", and an "api" subdir at
    // the workspace root that also has a stale `source.json`. Both detection
    // paths would yield "api"; the migration should only list it once.
    const fixture = makeCaseAWorkspace();
    // Remove the web sibling so only api remains.
    rmSync(join(fixture.workspaceRoot, "web"), { recursive: true, force: true });
    rmSync(join(fixture.treeRoot, ".first-tree", "bindings", "web-5678.json"));

    const detection = detectMigrationState(fixture.workspaceRoot);
    if (detection.kind !== "workspace") {
      throw new Error("expected workspace detection");
    }

    const result = migrateWorkspaceToW1(detection);

    expect(result.manifest.sources).toEqual(["api"]);
  });
});

describe("promoteToWorkspace (Case B/C)", () => {
  it("creates the workspace root and moves both repos into it", () => {
    const fixture = makeCaseBLayout();
    const detection = detectMigrationState(fixture.sourceRoot);
    if (detection.kind !== "promotable-source") {
      throw new Error("expected promotable-source detection");
    }

    const promote = promoteToWorkspace(detection);

    expect(existsSync(promote.workspaceRoot)).toBe(true);
    expect(existsSync(promote.newSourceRoot)).toBe(true);
    expect(existsSync(promote.newTreeRoot)).toBe(true);
    expect(existsSync(fixture.sourceRoot)).toBe(false);
    expect(existsSync(fixture.treeRoot)).toBe(false);
    expect(existsSync(join(promote.newSourceRoot, ".git"))).toBe(true);
    expect(existsSync(join(promote.newTreeRoot, ".git"))).toBe(true);
  });

  it("dry-run returns the planned paths without moving anything", () => {
    const fixture = makeCaseBLayout();
    const detection = detectMigrationState(fixture.sourceRoot);
    if (detection.kind !== "promotable-source") {
      throw new Error("expected promotable-source detection");
    }

    const plan = promoteToWorkspace(detection, { dryRun: true });

    expect(plan.dryRun).toBe(true);
    expect(existsSync(fixture.sourceRoot)).toBe(true);
    expect(existsSync(fixture.treeRoot)).toBe(true);
    expect(existsSync(plan.workspaceRoot)).toBe(false);
  });

  it("refuses to promote when the target workspace dir already exists", () => {
    const fixture = makeCaseBLayout();
    const detection = detectMigrationState(fixture.sourceRoot);
    if (detection.kind !== "promotable-source") {
      throw new Error("expected promotable-source detection");
    }
    // Pre-create the would-be workspace dir.
    mkdirSync(join(fixture.parentDir, detection.suggestedWorkspaceName));

    expect(() => promoteToWorkspace(detection)).toThrow(/already exists/u);
  });

  it("rejects workspace names containing path separators", () => {
    const fixture = makeCaseBLayout();
    const detection = detectMigrationState(fixture.sourceRoot);
    if (detection.kind !== "promotable-source") {
      throw new Error("expected promotable-source detection");
    }

    expect(() => promoteToWorkspace(detection, { workspaceName: "evil/path" })).toThrow(/Invalid/u);
    expect(() => promoteToWorkspace(detection, { workspaceName: "" })).toThrow(/Invalid/u);
    expect(() => promoteToWorkspace(detection, { workspaceName: "evil\\path" })).toThrow(/Invalid/u);
  });

  it("rolls back a partial promote when the tree move fails", () => {
    const fixture = makeCaseBLayout();
    const detection = detectMigrationState(fixture.sourceRoot);
    if (detection.kind !== "promotable-source") {
      throw new Error("expected promotable-source detection");
    }
    rmSync(fixture.treeRoot, { recursive: true, force: true });

    expect(() => promoteToWorkspace(detection)).toThrow();
    expect(existsSync(fixture.sourceRoot)).toBe(true);
    expect(existsSync(join(fixture.parentDir, detection.suggestedWorkspaceName))).toBe(false);
  });

  it("planPromotableDryRun reports the same cleanup the real run would do (Codex P2 / yuezengwu / code-reviewer / baixiaohang)", () => {
    // Regression: before the fix, dry-run computed cleanup against
    // post-move paths that did not exist yet, so the report was empty.
    // Now the dry-run runs against the pre-move layout and re-anchors
    // `workspaceRoot` to the planned location.
    const fixture = makeCaseBLayout();
    const detection = detectMigrationState(fixture.sourceRoot);
    if (detection.kind !== "promotable-source") {
      throw new Error("expected promotable-source detection");
    }
    const plannedRoot = join(fixture.parentDir, "my-workspace");

    const plan = planPromotableDryRun(detection, plannedRoot);

    expect(plan.dryRun).toBe(true);
    expect(plan.workspaceRoot).toBe(plannedRoot);
    expect(plan.manifest).toEqual({ tree: "context", sources: ["api"] });
    // The pre-move layout had: source.json, .agents/skills/, AGENTS.md
    // framework block, tree bindings/, tree.json. All should be in
    // `removed` / `modified`.
    const removedKinds = plan.removed.map((r) => r.kind);
    expect(removedKinds).toContain("source-state");
    expect(removedKinds).toContain("source-skills");
    expect(removedKinds).toContain("tree-bindings");
    expect(removedKinds).toContain("tree-state");
    const modifiedKinds = plan.modified.map((m) => m.kind);
    expect(modifiedKinds).toContain("source-framework-block");
  });

  it("end-to-end: promote then migrate yields a valid W1 workspace", () => {
    const fixture = makeCaseBLayout();
    const detection = detectMigrationState(fixture.sourceRoot);
    if (detection.kind !== "promotable-source") {
      throw new Error("expected promotable-source detection");
    }

    const promote = promoteToWorkspace(detection);
    const cleanup = migrateWorkspaceToW1(
      {
        kind: "workspace",
        workspaceRoot: promote.workspaceRoot,
        treeRoot: promote.newTreeRoot,
        sourceRoots: [promote.newSourceRoot],
      },
      {},
    );

    expect(cleanup.manifest).toEqual({ tree: "context", sources: ["api"] });
    expect(existsSync(join(promote.workspaceRoot, ".first-tree", "workspace.json"))).toBe(true);
    expect(existsSync(join(promote.newSourceRoot, ".first-tree", "source.json"))).toBe(false);
    expect(existsSync(join(promote.newTreeRoot, ".first-tree", "bindings"))).toBe(false);
  });
});
