DROP INDEX "uq_gitlab_entity_pending_chat";--> statement-breakpoint
DROP INDEX "uq_gitlab_entity_observed_chat";--> statement-breakpoint
ALTER TABLE "gitlab_entity_chat_mappings" ADD COLUMN "attention_mode" text DEFAULT 'legacy_route_only' NOT NULL;--> statement-breakpoint
ALTER TABLE "gitlab_entity_chat_mappings" ADD COLUMN "attention_backfill_version" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
CREATE UNIQUE INDEX "uq_gitlab_entity_pending_pair" ON "gitlab_entity_chat_mappings" USING btree ("connection_id","human_agent_id","delegate_agent_id","project_path_normalized","entity_type","entity_iid") WHERE "gitlab_entity_chat_mappings"."project_id" IS NULL AND "gitlab_entity_chat_mappings"."active" AND "gitlab_entity_chat_mappings"."bound_via" <> 'identity_target' AND "gitlab_entity_chat_mappings"."human_agent_id" IS NOT NULL AND "gitlab_entity_chat_mappings"."delegate_agent_id" IS NOT NULL;--> statement-breakpoint
CREATE UNIQUE INDEX "uq_gitlab_entity_observed_pair" ON "gitlab_entity_chat_mappings" USING btree ("connection_id","human_agent_id","delegate_agent_id","project_id","entity_type","entity_iid") WHERE "gitlab_entity_chat_mappings"."project_id" IS NOT NULL AND "gitlab_entity_chat_mappings"."active" AND "gitlab_entity_chat_mappings"."bound_via" <> 'identity_target' AND "gitlab_entity_chat_mappings"."human_agent_id" IS NOT NULL AND "gitlab_entity_chat_mappings"."delegate_agent_id" IS NOT NULL;--> statement-breakpoint
CREATE UNIQUE INDEX "uq_gitlab_entity_pending_legacy_chat" ON "gitlab_entity_chat_mappings" USING btree ("connection_id","chat_id","project_path_normalized","entity_type","entity_iid") WHERE "gitlab_entity_chat_mappings"."project_id" IS NULL AND "gitlab_entity_chat_mappings"."active" AND "gitlab_entity_chat_mappings"."bound_via" <> 'identity_target' AND "gitlab_entity_chat_mappings"."human_agent_id" IS NULL AND "gitlab_entity_chat_mappings"."delegate_agent_id" IS NULL;--> statement-breakpoint
CREATE UNIQUE INDEX "uq_gitlab_entity_observed_legacy_chat" ON "gitlab_entity_chat_mappings" USING btree ("connection_id","chat_id","project_id","entity_type","entity_iid") WHERE "gitlab_entity_chat_mappings"."project_id" IS NOT NULL AND "gitlab_entity_chat_mappings"."active" AND "gitlab_entity_chat_mappings"."bound_via" <> 'identity_target' AND "gitlab_entity_chat_mappings"."human_agent_id" IS NULL AND "gitlab_entity_chat_mappings"."delegate_agent_id" IS NULL;--> statement-breakpoint
ALTER TABLE "gitlab_entity_chat_mappings" ADD CONSTRAINT "ck_gitlab_entity_attention_pair" CHECK (("gitlab_entity_chat_mappings"."human_agent_id" IS NULL AND "gitlab_entity_chat_mappings"."delegate_agent_id" IS NULL) OR ("gitlab_entity_chat_mappings"."human_agent_id" IS NOT NULL AND "gitlab_entity_chat_mappings"."delegate_agent_id" IS NOT NULL));--> statement-breakpoint
ALTER TABLE "gitlab_entity_chat_mappings" ADD CONSTRAINT "ck_gitlab_entity_attention_mode" CHECK ("gitlab_entity_chat_mappings"."attention_mode" IN ('paired', 'legacy_route_only'));