import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  BINDING_CONTRACT_MARKER,
  BINDING_MODE_MARKER,
  ENTRYPOINT_MARKER,
  parseGitHubRepoReference,
  parseManagedSourceBindingText,
  SOURCE_INTEGRATION_BEGIN,
  SOURCE_INTEGRATION_END,
  SOURCE_INTEGRATION_FILES,
  SOURCE_INTEGRATION_MARKER,
  SOURCE_STATE_MARKER,
  TREE_MODE_MARKER,
  TREE_REPO_MARKER,
  TREE_REPO_SLUG_MARKER,
  TREE_REPO_URL_MARKER,
  WORKSPACE_ID_MARKER,
} from "./binding-contract.js";
import type { SourceBindingMode, TreeMode } from "./binding-state.js";
import { ensureTrailingNewline } from "./shared.js";
import type { ManagedFileAction } from "./skill-lib.js";

export type SourceIntegrationFile = "AGENTS.md" | "CLAUDE.md";

export type SourceIntegrationUpdate = {
  action: ManagedFileAction;
  file: SourceIntegrationFile;
};

export type SourceIntegrationOptions = {
  bindingMode?: SourceBindingMode;
  /**
   * Channel-resolved CLI binary name. Currently unused by the rendered block
   * (no executable CLI instruction remains), but accepted so callers that
   * already thread `channelConfig.binName` through don't need to change.
   */
  binName?: string;
  entrypoint?: string;
  sourceStatePath?: string;
  treeMode?: TreeMode;
  treeRepoName?: string;
  treeRepoUrl?: string;
  workspaceId?: string;
};

export type GitIgnoreUpdate = {
  action: "created" | "updated" | "unchanged";
  file: ".gitignore";
};

const LOCAL_TREE_TEMP_ROOT = ".first-tree/tmp";

const LOCAL_TREE_GITIGNORE_ENTRIES = [`${LOCAL_TREE_TEMP_ROOT}/`, ".agents/skills/", ".claude/skills/"] as const;

export function buildSourceIntegrationBlock(treeRepoName: string, options?: SourceIntegrationOptions): string {
  const details = deriveSourceIntegrationDetails(treeRepoName, options);

  return [
    SOURCE_INTEGRATION_BEGIN,
    "## First Tree integration",
    "",
    "> Managed block — regenerated by `first-tree` tooling. Do not edit by hand.",
    "",
    details.scopeText,
    "",
    "### Binding",
    "",
    ...details.bindingLines,
    "",
    "<!--",
    ...details.metadataLines,
    "-->",
    "",
    "### Before every task",
    "",
    "- Treat this managed block as the canonical local binding contract for which Context Tree this repo belongs to.",
    "- Use the recorded tree repo name, tree repo URL, and GitHub slug from this block as the source of truth when deciding which tree to read or update.",
    "- If you already have that tree repo cloned locally, update it before you read anything else.",
    details.fallbackInstruction,
    ...(details.sourceStatePathValue
      ? [
          `- If \`${details.sourceStatePathValue}\` exists, treat it as legacy migration state only. Do not edit it by hand.`,
        ]
      : []),
    `- Never commit anything under \`${LOCAL_TREE_TEMP_ROOT}/\` to this repo. It is local-only workspace state.`,
    "",
    "### After every task",
    "",
    "- If you suspect the task changed decisions, constraints, rationale, ownership, or shared workspace relationships, confirm whether the tree needs updating before opening any code PR — a tree PR is shared-state and externally visible, so the decision needs human endorsement when it is not obvious. Asking a human is [pending redesign, 自行判断].",
    "- If a tree update is needed (or the change is obviously tree-relevant), open the tree PR first, then the source/workspace code PR.",
    "- If the task changed only implementation details, skip the tree PR — open only the source/workspace code PR.",
    SOURCE_INTEGRATION_END,
  ].join("\n");
}

function deriveSourceIntegrationDetails(
  treeRepoName: string,
  options?: SourceIntegrationOptions,
): {
  bindingLines: string[];
  fallbackInstruction: string;
  metadataLines: string[];
  scopeText: string;
  sourceStatePathValue?: string;
} {
  // PR-C (audit Finding 7): the previous fallback default was
  // "standalone-source" — a legacy value that no W1 caller should ever
  // produce. After `upgradeSourceRoot` rejects pre-W1 bindings up
  // front, every reachable caller passes a `bindingMode` of
  // `workspace-root` or `workspace-member`. A reachable
  // `bindingMode === undefined` here is a bug; surface it loudly so
  // we don't silently rebuild legacy artifacts.
  if (options?.bindingMode === undefined) {
    throw new Error(
      "deriveSourceIntegrationDetails called without a bindingMode; W1 callers must pass workspace-root or workspace-member.",
    );
  }
  const bindingMode = options.bindingMode;
  const treeMode = options?.treeMode ?? "dedicated";
  const entrypoint = options?.entrypoint ?? "/";
  const sourceStatePathValue = options?.sourceStatePath;
  const resolvedTreeRepoName = options?.treeRepoName ?? treeRepoName;
  const treeRepoUrl = options?.treeRepoUrl?.trim() || null;
  const treeRepoSlug = parseGitHubRepoReference(treeRepoUrl ?? undefined) ?? null;
  const workspaceId = options?.workspaceId?.trim() || null;

  return {
    bindingLines: buildBindingLines(
      resolvedTreeRepoName,
      treeRepoSlug,
      bindingMode,
      entrypoint,
      workspaceId,
      treeRepoUrl,
    ),
    fallbackInstruction: buildFallbackInstruction(treeRepoName, treeRepoUrl),
    metadataLines: buildMetadataLines(
      treeRepoName,
      resolvedTreeRepoName,
      treeRepoSlug,
      bindingMode,
      treeMode,
      entrypoint,
      workspaceId,
      treeRepoUrl,
      sourceStatePathValue,
    ),
    scopeText: describeScope(bindingMode, treeMode, treeRepoName, workspaceId),
    sourceStatePathValue,
  };
}

function buildBindingLines(
  resolvedTreeRepoName: string,
  treeRepoSlug: string | null,
  bindingMode: SourceBindingMode,
  entrypoint: string,
  workspaceId: string | null,
  treeRepoUrl: string | null,
): string[] {
  return [
    `- **Tree repo:** \`${resolvedTreeRepoName}\``,
    ...(treeRepoSlug === null ? [] : [`- **GitHub tree repo:** \`${treeRepoSlug}\``]),
    `- **Binding mode:** \`${bindingMode}\``,
    `- **Entrypoint:** \`${entrypoint}\``,
    ...(workspaceId === null ? [] : [`- **Workspace ID:** \`${workspaceId}\``]),
    `- **Tree repo URL:** ${formatTreeRepoUrlDisplay(treeRepoUrl)}`,
  ];
}

function buildMetadataLines(
  treeRepoName: string,
  resolvedTreeRepoName: string,
  treeRepoSlug: string | null,
  bindingMode: SourceBindingMode,
  treeMode: TreeMode,
  entrypoint: string,
  workspaceId: string | null,
  treeRepoUrl: string | null,
  sourceStatePathValue: string | undefined,
): string[] {
  return [
    `${BINDING_CONTRACT_MARKER} managed-block-v1`,
    `${SOURCE_INTEGRATION_MARKER} ${describeBinding(bindingMode, treeMode, treeRepoName)}`,
    `${TREE_REPO_MARKER} \`${resolvedTreeRepoName}\``,
    ...(treeRepoSlug === null ? [] : [`${TREE_REPO_SLUG_MARKER} \`${treeRepoSlug}\``]),
    `${TREE_MODE_MARKER} \`${treeMode}\``,
    `${BINDING_MODE_MARKER} \`${bindingMode}\``,
    `${TREE_REPO_URL_MARKER} ${treeRepoUrl === null ? "pending publish" : `\`${treeRepoUrl}\``}`,
    `${ENTRYPOINT_MARKER} \`${entrypoint}\``,
    ...(workspaceId === null ? [] : [`${WORKSPACE_ID_MARKER} \`${workspaceId}\``]),
    ...(sourceStatePathValue ? [`${SOURCE_STATE_MARKER} \`${sourceStatePathValue}\``] : []),
  ];
}

function formatTreeRepoUrlDisplay(treeRepoUrl: string | null): string {
  return treeRepoUrl === null ? "_pending publish_" : `<${treeRepoUrl}>`;
}

function buildFallbackInstruction(treeRepoName: string, treeRepoUrl: string | null): string {
  if (treeRepoUrl === null) {
    return "- If the tree has not been pushed to GitHub yet, work from the local checkout (or pass `--tree-path` explicitly) until the tree repo has a remote URL.";
  }

  return `- If you do not already have that tree repo cloned locally, clone a temporary working copy from \`${treeRepoUrl}\` into \`${join(LOCAL_TREE_TEMP_ROOT, treeRepoName)}/\`, use it for the current task, and delete it before you finish.`;
}

function describeBinding(bindingMode: SourceBindingMode, treeMode: TreeMode, treeRepoName: string): string {
  switch (bindingMode) {
    case "workspace-root":
      return `workspace root bound to shared tree repo \`${treeRepoName}\``;
    case "workspace-member":
      return `workspace member bound to shared tree repo \`${treeRepoName}\``;
    case "shared-source":
      return `source repo bound to shared tree repo \`${treeRepoName}\``;
    default:
      return treeMode === "shared"
        ? `source repo bound to shared tree repo \`${treeRepoName}\``
        : `source repo bound to dedicated tree repo \`${treeRepoName}\``;
  }
}

function describeScope(
  bindingMode: SourceBindingMode,
  treeMode: TreeMode,
  treeRepoName: string,
  workspaceId: string | null,
): string {
  switch (bindingMode) {
    case "workspace-root":
      return `This folder is a workspace root. Install first-tree locally here, keep all Context Tree files only in the shared \`${treeRepoName}\` repo, and keep child repos bound to the same tree${workspaceId === null ? "" : ` for workspace \`${workspaceId}\``}.`;
    case "workspace-member":
      return `This repo is a workspace member. Keep all Context Tree files only in the shared \`${treeRepoName}\` repo and follow the workspace root's binding for shared context updates${workspaceId === null ? "" : ` in workspace \`${workspaceId}\``}.`;
    case "shared-source":
      return `This repo is bound to an existing shared Context Tree. Keep all Context Tree files only in the shared \`${treeRepoName}\` repo.`;
    default:
      return treeMode === "shared"
        ? `This repo is bound to a shared Context Tree. Keep all Context Tree files only in the shared \`${treeRepoName}\` repo.`
        : `This repo is a source/workspace repo. Keep all Context Tree files only in the dedicated \`${treeRepoName}\` repo.`;
  }
}

export function upsertSourceIntegrationFiles(
  root: string,
  treeRepoName: string,
  options?: SourceIntegrationOptions,
): SourceIntegrationUpdate[] {
  return SOURCE_INTEGRATION_FILES.map((file) => upsertSourceIntegrationFile(root, file, treeRepoName, options));
}

function upsertSourceIntegrationFile(
  root: string,
  file: SourceIntegrationFile,
  treeRepoName: string,
  options?: SourceIntegrationOptions,
): SourceIntegrationUpdate {
  const fullPath = join(root, file);
  const exists = existsSync(fullPath);
  const current = exists ? readFileSync(fullPath, "utf-8") : "";
  const normalized = current.replaceAll("\r\n", "\n");
  const nextBlock = buildSourceIntegrationBlock(
    treeRepoName,
    deriveIntegrationOptions(normalized, treeRepoName, options),
  );
  const nextText = replaceManagedSourceIntegrationBlock(normalized, nextBlock);

  if (ensureTrailingNewline(nextText) === ensureTrailingNewline(normalized)) {
    return { action: "unchanged", file };
  }

  writeFileSync(fullPath, ensureTrailingNewline(nextText));
  return { action: exists ? "updated" : "created", file };
}

function deriveIntegrationOptions(
  normalized: string,
  treeRepoName: string,
  options?: SourceIntegrationOptions,
): SourceIntegrationOptions {
  const existing = parseManagedSourceBindingText(normalized);

  return {
    bindingMode: firstDefined(options?.bindingMode, existing?.bindingMode),
    entrypoint: firstDefined(options?.entrypoint, existing?.entrypoint),
    sourceStatePath: firstDefined(options?.sourceStatePath),
    treeMode: firstDefined(options?.treeMode, existing?.treeMode),
    treeRepoName: firstDefined(options?.treeRepoName, existing?.treeRepoName, treeRepoName),
    treeRepoUrl: firstDefined(options?.treeRepoUrl, existing?.treeRepoUrl),
    workspaceId: firstDefined(options?.workspaceId, existing?.workspaceId),
  };
}

function firstDefined<T>(...values: Array<T | null | undefined>): T | undefined {
  for (const value of values) {
    if (value !== undefined && value !== null) {
      return value;
    }
  }
  return undefined;
}

function replaceManagedSourceIntegrationBlock(normalized: string, nextBlock: string): string {
  const managedBlock =
    /<!-- BEGIN FIRST-TREE-SOURCE-INTEGRATION -->[\s\S]*?<!-- END FIRST-TREE-SOURCE-INTEGRATION -->\n?/mu;
  return managedBlock.test(normalized)
    ? normalized.replace(managedBlock, `${nextBlock}\n`)
    : appendManagedBlock(normalized, nextBlock);
}

function appendManagedBlock(current: string, nextBlock: string): string {
  const trimmed = current.trimEnd();
  if (trimmed.length === 0) {
    return `${nextBlock}\n`;
  }
  return `${trimmed}\n\n${nextBlock}\n`;
}

export function upsertLocalTreeGitIgnore(root: string): GitIgnoreUpdate {
  const fullPath = join(root, ".gitignore");
  const exists = existsSync(fullPath);
  const current = exists ? readFileSync(fullPath, "utf-8") : "";
  const lines = current
    .replaceAll("\r\n", "\n")
    .split("\n")
    .filter((line, index, source) => {
      if (index === source.length - 1 && line === "") {
        return false;
      }
      return true;
    });

  let changed = false;

  for (const entry of LOCAL_TREE_GITIGNORE_ENTRIES) {
    if (!lines.includes(entry)) {
      lines.push(entry);
      changed = true;
    }
  }

  if (!changed) {
    return { action: "unchanged", file: ".gitignore" };
  }

  writeFileSync(fullPath, ensureTrailingNewline(lines.join("\n")));
  return { action: exists ? "updated" : "created", file: ".gitignore" };
}

// PR-C (audit Finding 2): `ensureWhitepaperSymlink`,
// `readManagedWhitepaperTarget`, and `removeManagedWhitepaper` were
// the source/tree-root WHITEPAPER.md plumbing for the pre-W1 layout.
// PR-A removed the tree-root call sites (init + upgrade-tree path),
// PR-A round 2 closed the upgrade-tree-root path, and PR-C closes the
// last reachable caller by making `upgradeSourceRoot` reject legacy
// bindings. With nothing in the live tree calling these helpers, the
// definitions go too. Callers that want to verify a tree subdir does
// NOT contain WHITEPAPER.md can check via plain `existsSync`. The
// migrate cleanup path in `apps/cli/src/core/migrate-workspace.ts`
// has always used its own `tryRemove` against `WHITEPAPER.md` and is
// unaffected.
