import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

import { listTreeBindings, TREE_CODE_REPOS_FILE } from "./binding-state.js";
import { ensureTrailingNewline, parseGitHubRemoteUrl } from "./shared.js";

const CODE_REPOS_SCHEMA_VERSION = 1;

type CodeReposFile = {
  repos: ManagedTreeCodeRepo[];
  schemaVersion: number;
};

const TREE_CODE_REPO_REGISTRY_BEGIN = "<!-- BEGIN FIRST-TREE-CODE-REPO-REGISTRY -->";
const TREE_CODE_REPO_REGISTRY_END = "<!-- END FIRST-TREE-CODE-REPO-REGISTRY -->";
const TREE_CODE_REPO_REGISTRY_MARKER = "FIRST-TREE-CODE-REPO-REGISTRY:";
const TREE_CODE_REPO_MARKER = "FIRST-TREE-CODE-REPO:";
const TREE_REGISTRY_FILES = ["AGENTS.md", "CLAUDE.md"] as const;

export type ManagedTreeCodeRepo = {
  name: string;
  slug: string;
  url: string;
};

type SyncAction = "created" | "updated" | "unchanged" | "skipped";

function escapeForRegExp(text: string): string {
  return text.replace(/[.*+?^${}()|[\]\\]/gu, "\\$&");
}

function normalizeGitHubRepoUrl(value: string): ManagedTreeCodeRepo | undefined {
  const parsed = parseGitHubRemoteUrl(value);

  if (parsed === null || parsed.host.toLowerCase() !== "github.com") {
    return undefined;
  }

  return {
    name: parsed.repo,
    slug: `${parsed.owner}/${parsed.repo}`,
    url: `https://${parsed.host}/${parsed.owner}/${parsed.repo}`,
  };
}

function dedupeRepos(repos: ManagedTreeCodeRepo[]): ManagedTreeCodeRepo[] {
  return [...new Map(repos.map((repo) => [repo.slug, repo])).values()].sort((left, right) =>
    left.slug.localeCompare(right.slug),
  );
}

function extractManagedBlock(text: string): string | undefined {
  const normalized = text.replaceAll("\r\n", "\n");
  const managedBlock = new RegExp(
    `${escapeForRegExp(TREE_CODE_REPO_REGISTRY_BEGIN)}[\\s\\S]*?${escapeForRegExp(TREE_CODE_REPO_REGISTRY_END)}`,
    "mu",
  );

  return normalized.match(managedBlock)?.[0];
}

function parseManagedRepos(text: string): ManagedTreeCodeRepo[] {
  const block = extractManagedBlock(text);

  if (block === undefined) {
    return [];
  }

  const matches = [...block.matchAll(/^FIRST-TREE-CODE-REPO:\s+`(.+?)`\s*$/gmu)];
  return dedupeRepos(
    matches
      .map((match) => normalizeGitHubRepoUrl(match[1]))
      .filter((value): value is ManagedTreeCodeRepo => value !== undefined),
  );
}

function fallbackReposFromBindings(treeRoot: string): ManagedTreeCodeRepo[] {
  return dedupeRepos(
    listTreeBindings(treeRoot)
      .map((binding) => binding.remoteUrl)
      .filter((value): value is string => typeof value === "string" && value.length > 0)
      .map((value) => normalizeGitHubRepoUrl(value))
      .filter((value): value is ManagedTreeCodeRepo => value !== undefined),
  );
}

function registryBlock(repos: ManagedTreeCodeRepo[]): string {
  return [
    TREE_CODE_REPO_REGISTRY_BEGIN,
    "## Managed Code Repos",
    "",
    "> Managed block — regenerated by `first-tree` tooling. Do not edit by hand.",
    "",
    ...(repos.length === 0
      ? ["No managed code repos have been recorded yet."]
      : repos.map((repo) => `- [${repo.slug}](${repo.url})`)),
    "",
    "<!--",
    `${TREE_CODE_REPO_REGISTRY_MARKER} managed-block-v1`,
    ...repos.map((repo) => `${TREE_CODE_REPO_MARKER} \`${repo.url}\``),
    "-->",
    TREE_CODE_REPO_REGISTRY_END,
  ].join("\n");
}

function upsertManagedBlock(text: string, block: string): string {
  const normalized = ensureTrailingNewline(text.replaceAll("\r\n", "\n"));
  const managedBlock = new RegExp(
    `${escapeForRegExp(TREE_CODE_REPO_REGISTRY_BEGIN)}[\\s\\S]*?${escapeForRegExp(TREE_CODE_REPO_REGISTRY_END)}\\n?`,
    "mu",
  );

  if (managedBlock.test(normalized)) {
    return ensureTrailingNewline(normalized.replace(managedBlock, `${block}\n`));
  }

  const insertBefore = /^# Project-Specific Instructions\s*$/mu.exec(normalized);

  if (insertBefore && insertBefore.index >= 0) {
    return ensureTrailingNewline(
      [normalized.slice(0, insertBefore.index).trimEnd(), block, normalized.slice(insertBefore.index).trimStart()]
        .filter(Boolean)
        .join("\n\n"),
    );
  }

  const insertAfter = /<!-- END CONTEXT-TREE FRAMEWORK -->\s*/mu.exec(normalized);

  if (insertAfter && insertAfter.index >= 0) {
    const insertAt = insertAfter.index + insertAfter[0].length;
    return ensureTrailingNewline(
      [normalized.slice(0, insertAt).trimEnd(), block, normalized.slice(insertAt).trimStart()]
        .filter(Boolean)
        .join("\n\n"),
    );
  }

  return ensureTrailingNewline(`${normalized.trimEnd()}\n\n${block}`);
}

function writeRegistryFile(path: string, repos: ManagedTreeCodeRepo[]): SyncAction {
  const current = existsSync(path) ? readFileSync(path, "utf-8") : null;
  const next = upsertManagedBlock(current ?? "", registryBlock(repos));

  if (current === next) {
    return "unchanged";
  }

  writeFileSync(path, next);
  return current === null ? "created" : "updated";
}

function readCodeReposFile(treeRoot: string): ManagedTreeCodeRepo[] {
  const path = join(treeRoot, TREE_CODE_REPOS_FILE);

  if (!existsSync(path)) {
    return [];
  }

  try {
    const parsed = JSON.parse(readFileSync(path, "utf-8")) as unknown;
    if (
      typeof parsed === "object" &&
      parsed !== null &&
      "repos" in parsed &&
      Array.isArray((parsed as { repos: unknown }).repos)
    ) {
      const file = parsed as CodeReposFile;
      return dedupeRepos(
        file.repos
          .map((repo) => normalizeGitHubRepoUrl(repo.url))
          .filter((repo): repo is ManagedTreeCodeRepo => repo !== undefined),
      );
    }
  } catch {
    // fall through to empty
  }

  return [];
}

function writeCodeReposFile(treeRoot: string, repos: ManagedTreeCodeRepo[]): SyncAction {
  const path = join(treeRoot, TREE_CODE_REPOS_FILE);
  const next = `${JSON.stringify({ repos, schemaVersion: CODE_REPOS_SCHEMA_VERSION }, null, 2)}\n`;
  const current = existsSync(path) ? readFileSync(path, "utf-8") : null;

  if (current === next) {
    return "unchanged";
  }

  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, next);
  return current === null ? "created" : "updated";
}

export function listKnownTreeCodeRepos(treeRoot: string): ManagedTreeCodeRepo[] {
  // `.first-tree/code-repos.json` is the canonical store. Tree-root
  // `AGENTS.md` / `CLAUDE.md` were the v0.x storage and are read here only as
  // a legacy fallback (those files are no longer generated; see #794). When
  // both are empty, fall back to walking the source bindings directory.
  const persisted = readCodeReposFile(treeRoot);
  if (persisted.length > 0) {
    return persisted;
  }

  for (const file of TREE_REGISTRY_FILES) {
    const path = join(treeRoot, file);

    if (!existsSync(path)) {
      continue;
    }

    const repos = parseManagedRepos(readFileSync(path, "utf-8"));

    if (repos.length > 0) {
      return repos;
    }
  }

  return fallbackReposFromBindings(treeRoot);
}

export function syncTreeCodeRepoRegistry(treeRoot: string, repoUrls: string[]): SyncAction {
  const repos = dedupeRepos(
    repoUrls
      .map((value) => normalizeGitHubRepoUrl(value))
      .filter((value): value is ManagedTreeCodeRepo => value !== undefined),
  );

  // Canonical write: always persist to `.first-tree/code-repos.json`.
  let overallAction: SyncAction = writeCodeReposFile(treeRoot, repos);

  // Legacy mirrors: if tree-root `AGENTS.md` / `CLAUDE.md` still exist on an
  // older tree, keep their managed registry block in sync. New trees no
  // longer generate these files so this loop is a no-op for them.
  for (const file of TREE_REGISTRY_FILES) {
    const path = join(treeRoot, file);

    if (!existsSync(path)) {
      continue;
    }

    const action = writeRegistryFile(path, repos);
    if (action === "created" || action === "updated") {
      overallAction = action;
    }
  }

  return overallAction;
}

export function upsertTreeCodeRepoRegistry(treeRoot: string, repoUrl: string): SyncAction {
  const repo = normalizeGitHubRepoUrl(repoUrl);

  if (repo === undefined) {
    return "skipped";
  }

  return syncTreeCodeRepoRegistry(treeRoot, [...listKnownTreeCodeRepos(treeRoot).map((entry) => entry.url), repo.url]);
}

function formatRemoteCell(repo: ManagedTreeCodeRepo): string {
  const github = parseGitHubRemoteUrl(repo.url);

  if (github === null || github.host !== "github.com") {
    return `\`${repo.url}\``;
  }

  const webUrl = `https://${github.host}/${github.owner}/${github.repo}`;
  return `[${github.owner}/${github.repo}](${webUrl})`;
}

/**
 * Render the `## Managed Code Repos` table that
 * `tree-first-context.ts` embeds in the agent-context payload. Lives
 * here because it operates on `ManagedTreeCodeRepo[]` which this
 * module owns; previously lived in the now-removed
 * `source-repo-index.ts` writer module.
 */
export function buildSourceRepoIndexTable(repos: ManagedTreeCodeRepo[]): string[] {
  if (repos.length === 0) {
    return ["No managed code repos have been recorded yet."];
  }

  const lines = ["| Source | GitHub |", "| --- | --- |"];

  for (const repo of repos) {
    lines.push([`| \`${repo.name}\``, `${formatRemoteCell(repo)} |`].join(" | "));
  }

  return lines;
}
