// biome-ignore-all lint/suspicious/noTemplateCurlyInString: this file emits GitHub Actions workflow YAML; `${{ ... }}` is the expression syntax and must remain a literal.

export function renderRootNode(treeTitle: string): string {
  return [
    "---",
    `title: "${treeTitle}"`,
    "owners: []",
    "---",
    "",
    `# ${treeTitle}`,
    "",
    "The living source of truth for your organization. A structured knowledge base that agents and humans build and maintain together across one or more source repositories and systems.",
    "",
    "---",
    "",
    "## Domains",
    "",
    "- **[members/](members/NODE.md)** — Team member definitions and responsibilities.",
    "",
    "---",
    "",
    "## Working with the Tree",
    "",
    "Keep decision context here. Keep implementation detail in the source repos this tree describes.",
    "",
    "See [AGENTS.md](AGENTS.md) for agent instructions — the before/during/after workflow, ownership model, and tree maintenance.",
    "",
  ].join("\n");
}

export function renderMembersDomainNode(): string {
  return [
    "---",
    'title: "Members"',
    "owners: []",
    "---",
    "",
    "# Members",
    "",
    "Member definitions, work scope, and personal node specifications.",
    "",
  ].join("\n");
}

export function renderDefaultMemberNode(memberTitle = "Owner"): string {
  return [
    "---",
    `title: "${memberTitle}"`,
    "owners: []",
    "type: human",
    "role: owner",
    "domains: [core]",
    "---",
    "",
    `# ${memberTitle}`,
    "",
    "Default bootstrap member node. Update this once the real member roster is known.",
    "",
  ].join("\n");
}

export function renderDeveloperAgentTemplate(): string {
  return [
    "name: developer",
    "prompt: |",
    "  Default First Tree developer agent.",
    "  Use First Tree context before changing cross-repo decisions or ownership.",
    "skills:",
    "  - .agents/skills/first-tree",
    "  - .agents/skills/first-tree-sync",
    "  - .agents/skills/first-tree-write",
    "  - .agents/skills/first-tree-github-scan",
    "runtime: codex",
    "workspace:",
    "  kind: worktree",
    "env: {}",
    "auth:",
    "  github:",
    "    provider: env",
    "    variable: GITHUB_TOKEN",
    "mcp: []",
    "",
  ].join("\n");
}

export function renderCodeReviewerAgentTemplate(): string {
  return [
    "name: code-reviewer",
    "prompt: |",
    "  Default First Tree code review agent.",
    "  Focus on review quality, tree implications, and when human escalation is required.",
    "skills:",
    "  - .agents/skills/first-tree",
    "  - .agents/skills/first-tree-sync",
    "  - .agents/skills/first-tree-write",
    "  - .agents/skills/first-tree-github-scan",
    "runtime: codex",
    "workspace:",
    "  kind: worktree",
    "env: {}",
    "auth:",
    "  github:",
    "    provider: env",
    "    variable: GITHUB_TOKEN",
    "mcp: []",
    "",
  ].join("\n");
}

export function renderOrgConfigPlaceholder(): string {
  return [
    "agents: []",
    "collaboration:",
    "  routing: []",
    "  review: []",
    "humanInvolveRules:",
    "  defaults:",
    "    - missing-owner",
    "    - cross-domain-impact",
    "    - unknown-decision",
    "companyContext:",
    '  industry: ""',
    '  stage: ""',
    "  techStackConstraints: []",
    "  culture: []",
    "",
  ].join("\n");
}

export function renderValidateWorkflow(cliVersion: string): string {
  return [
    "# first-tree-template-version: 2",
    "name: Validate Tree",
    "",
    "on:",
    "  # Trigger on every PR (no paths filter), so the `validate` status check is",
    "  # always reported. Branch protection lists this check as required; if the",
    "  # workflow doesn't run, the PR remains blocked. `tree verify` validates the",
    "  # tree state regardless of which files the PR changed and is fast (~1s).",
    "  pull_request:",
    "",
    "jobs:",
    "  validate:",
    "    runs-on: ubuntu-latest",
    "    steps:",
    "      - uses: actions/checkout@v4",
    "",
    "      - uses: actions/setup-node@v4",
    "        with:",
    '          node-version: "22"',
    "",
    "      - name: Validate tree",
    `        run: npx -p first-tree@${cliVersion} first-tree tree verify`,
  ].join("\n");
}

export function renderAutoMergeWorkflow(): string {
  return [
    "# first-tree-template-version: 1",
    "name: Auto-merge gate",
    "",
    "# Tiered write workflow gate, driven by frontmatter `owners` as the source",
    "# of truth (no GitHub PR review approval involved):",
    "#",
    "# - personal: PR only changes `members/<author>/**` and every commit's",
    "#   committer matches the author -> gate passes",
    "# - self-owner / [*]: author is in the intersection of frontmatter `owners`",
    "#   across all changed files (with `owners: [*]` expanded to all members'",
    "#   GitHub usernames from `members/<*>/NODE.md` frontmatter) -> gate passes",
    "# - cross-owner: gate fails until an owner in the intersection submits an",
    "#   APPROVED review on the PR (workflow re-runs on review submission)",
    "#",
    "# After the gate passes for personal/self_owner PRs, the workflow uses a",
    "# GitHub App installation token to enable GitHub's auto-merge so the PR",
    "# squash-lands as soon as `validate` is green. Failure to enable is logged",
    "# as a warning. cross_owner PRs are not auto-enabled; owners merge them",
    "# manually after review.",
    "#",
    "# Configuration (one-time):",
    "# - GitHub App `first-tree-gate` with `Pull requests: Read and write`",
    "#   (no other permissions needed) installed on the repo. App ID and",
    "#   private key stored as repo secrets `GATE_APP_ID` and",
    "#   `GATE_APP_PRIVATE_KEY`.",
    "# - Repository ruleset: `gate` and `validate` in required status checks.",
    "#   `Require approvals: 1`, `Require review from Code Owners: off`.",
    "# - Classic branch protection on the same branch MUST be deleted -",
    "#   classic + ruleset stack as a union of constraints, and any leftover",
    "#   contexts/required reviews in classic will block PRs invisibly.",
    "",
    "on:",
    "  pull_request:",
    "    types: [opened, synchronize, reopened, ready_for_review]",
    "  pull_request_review:",
    "    types: [submitted, dismissed]",
    "",
    "permissions:",
    "  contents: read",
    "  pull-requests: write",
    "",
    "jobs:",
    "  gate:",
    "    runs-on: ubuntu-latest",
    "    if: github.event.pull_request.draft == false",
    "    steps:",
    "      - uses: actions/checkout@v4",
    "        with:",
    "          # Read owners from BASE - a PR cannot inject owners into its own gate.",
    "          ref: ${{ github.event.pull_request.base.sha }}",
    "          fetch-depth: 0",
    "",
    "      - name: Classify PR",
    "        id: classify",
    "        uses: actions/github-script@v7",
    "        with:",
    "          script: |",
    "            const fs = require('fs');",
    "            const { execFileSync } = require('child_process');",
    "",
    "            const author = context.payload.pull_request.user.login;",
    "            const prNumber = context.payload.pull_request.number;",
    "            const baseSha = context.payload.pull_request.base.sha;",
    "            core.setOutput('author', author);",
    "",
    "            function classify(label, reason, ownersIntersection) {",
    "              core.info(`PR ${prNumber}: ${label} - ${reason}`);",
    "              core.setOutput('classification', label);",
    "              core.setOutput('reason', reason);",
    "              core.setOutput('ownersIntersection', (ownersIntersection || []).join(','));",
    "            }",
    "",
    "            // ---- Collect changed files ----",
    "            const files = await github.paginate(github.rest.pulls.listFiles, {",
    "              owner: context.repo.owner,",
    "              repo: context.repo.repo,",
    "              pull_number: prNumber,",
    "              per_page: 100,",
    "            });",
    "",
    "            // ---- Personal: members/<author>/** + matching committer ----",
    "            const personalPrefix = `members/${author}/`;",
    "            const allPersonal = files.length > 0 &&",
    "              files.every((f) => f.filename.startsWith(personalPrefix));",
    "            if (allPersonal) {",
    "              const commits = await github.paginate(github.rest.pulls.listCommits, {",
    "                owner: context.repo.owner,",
    "                repo: context.repo.repo,",
    "                pull_number: prNumber,",
    "                per_page: 100,",
    "              });",
    "              const allCommitterMatches = commits.every((c) => {",
    "                const login = c.committer && c.committer.login;",
    "                return login === author;",
    "              });",
    "              if (allCommitterMatches) {",
    "                classify('personal', `members/${author}/** + committer = author`);",
    "                return;",
    "              }",
    "              const offenders = commits",
    "                .filter((c) => !c.committer || c.committer.login !== author)",
    "                .map((c) => `${c.sha.slice(0, 7)} (${c.committer ? c.committer.login : 'unknown'})`)",
    "                .join(', ');",
    "              classify('cross_owner', `personal-path PR but committer mismatch: ${offenders}`, [author]);",
    "              return;",
    "            }",
    "",
    "            // ---- All-members list (for `[*]` expansion) ----",
    "            // Reads each `members/<dir>/NODE.md`'s `owners` frontmatter,",
    "            // because directory slugs may differ from GitHub usernames.",
    "            function parseInlineOwners(content) {",
    "              const fmMatch = content.match(/^---\\s*\\n([\\s\\S]*?)\\n---/);",
    "              if (!fmMatch) return null;",
    "              const fm = fmMatch[1];",
    "              const inline = fm.match(/^owners:\\s*\\[([^\\]]*)\\]/m);",
    "              if (inline) {",
    "                const raw = inline[1].trim();",
    "                if (!raw || raw === '*') return null;",
    "                return raw",
    "                  .split(',')",
    "                  .map((s) => s.trim().replace(/^['\"]|['\"]$/g, ''))",
    "                  .filter(Boolean);",
    "              }",
    "              const block = fm.match(/^owners:\\s*\\n((?:\\s+-\\s+.+\\n?)+)/m);",
    "              if (block) {",
    "                return block[1]",
    "                  .trim()",
    "                  .split('\\n')",
    "                  .map((line) =>",
    "                    line.replace(/#.*$/, '').trim().replace(/^-\\s*/, '').trim().replace(/^['\"]|['\"]$/g, ''),",
    "                  )",
    "                  .filter(Boolean);",
    "              }",
    "              return null;",
    "            }",
    "",
    "            const allMembers = fs.readdirSync('members', { withFileTypes: true })",
    "              .filter((e) => e.isDirectory())",
    "              .flatMap((e) => {",
    "                try {",
    "                  const content = fs.readFileSync(`members/${e.name}/NODE.md`, 'utf-8');",
    "                  const owners = parseInlineOwners(content);",
    "                  if (owners && owners.length > 0) return owners;",
    "                } catch {",
    "                  // Fall through.",
    "                }",
    "                return [e.name];",
    "              });",
    "",
    "            // ---- Self-owner / [*]: author in owners intersection ----",
    "            function readBaseContent(path) {",
    "              try {",
    "                return execFileSync('git', ['show', `${baseSha}:${path}`], {",
    "                  encoding: 'utf-8',",
    "                });",
    "              } catch {",
    "                return null;",
    "              }",
    "            }",
    "",
    "            function parseOwnersField(content) {",
    "              const fmMatch = content.match(/^---\\s*\\n([\\s\\S]*?)\\n---/);",
    "              if (!fmMatch) return null;",
    "              const fm = fmMatch[1];",
    "",
    "              const inline = fm.match(/^owners:\\s*\\[([^\\]]*)\\]/m);",
    "              if (inline) {",
    "                const raw = inline[1].trim();",
    "                if (raw === '*') return [...allMembers];",
    "                if (!raw) return null;",
    "                return raw",
    "                  .split(',')",
    "                  .map((s) => s.trim().replace(/^['\"]|['\"]$/g, ''))",
    "                  .filter(Boolean);",
    "              }",
    "",
    "              const block = fm.match(/^owners:\\s*\\n((?:\\s+-\\s+.+\\n?)+)/m);",
    "              if (block) {",
    "                return block[1]",
    "                  .trim()",
    "                  .split('\\n')",
    "                  .map((line) =>",
    "                    line.replace(/#.*$/, '').trim().replace(/^-\\s*/, '').trim().replace(/^['\"]|['\"]$/g, ''),",
    "                  )",
    "                  .filter(Boolean);",
    "              }",
    "",
    "              return null;",
    "            }",
    "",
    "            const ownerSets = [];",
    "            for (const file of files) {",
    "              if (!file.filename.endsWith('.md')) {",
    "                classify('cross_owner', `non-markdown file ${file.filename}`, allMembers);",
    "                return;",
    "              }",
    "              if (file.status === 'renamed') {",
    "                classify(",
    "                  'cross_owner',",
    "                  `${file.filename} renamed from ${file.previous_filename}`,",
    "                  allMembers,",
    "                );",
    "                return;",
    "              }",
    "              if (file.status === 'added' && !file.filename.startsWith('members/')) {",
    "                classify('cross_owner', `new file ${file.filename}`, allMembers);",
    "                return;",
    "              }",
    "",
    "              const personalMatch = file.filename.match(/^members\\/([^/]+)\\//);",
    "              if (personalMatch) {",
    "                ownerSets.push([personalMatch[1]]);",
    "                continue;",
    "              }",
    "",
    "              const content = readBaseContent(file.filename);",
    "              if (content === null) {",
    "                classify('cross_owner', `could not read base content for ${file.filename}`, allMembers);",
    "                return;",
    "              }",
    "              const owners = parseOwnersField(content);",
    "              if (owners === null || owners.length === 0) {",
    "                classify('cross_owner', `${file.filename} has no usable owners field at base`, allMembers);",
    "                return;",
    "              }",
    "              ownerSets.push(owners);",
    "            }",
    "",
    "            if (ownerSets.length === 0) {",
    "              classify('cross_owner', 'no markdown files changed', allMembers);",
    "              return;",
    "            }",
    "",
    "            let intersection = ownerSets[0];",
    "            for (let i = 1; i < ownerSets.length; i++) {",
    "              intersection = intersection.filter((o) => ownerSets[i].includes(o));",
    "            }",
    "",
    "            if (intersection.includes(author)) {",
    "              classify(",
    "                'self_owner',",
    "                `author in owners intersection: [${intersection.join(', ')}]`,",
    "                intersection,",
    "              );",
    "            } else {",
    "              classify(",
    "                'cross_owner',",
    "                `author not in owners intersection: [${intersection.join(', ')}]`,",
    "                intersection,",
    "              );",
    "            }",
    "",
    "      # Cross-owner PRs are not gated by this workflow itself - the ruleset's",
    "      # `required_approving_review_count: 1` requires an APPROVED review.",
    "      # The companion `review-enforcer.yml` workflow dismisses approvals from",
    "      # users not listed in the file's frontmatter `owners`, so cross_owner",
    "      # PRs must be approved by a frontmatter-listed owner specifically.",
    "",
    "      # Generate an installation token for the gate App. Used to submit the",
    "      # bot's APPROVED review (counts toward the 1-approval requirement) and",
    "      # to call enablePullRequestAutoMerge. Skipped on cross_owner - those",
    "      # PRs need a real owner's approval.",
    "      - name: Generate App token",
    "        if: success() && steps.classify.outputs.classification != 'cross_owner'",
    "        id: app-token",
    "        uses: actions/create-github-app-token@v1",
    "        with:",
    "          app-id: ${{ secrets.GATE_APP_ID }}",
    "          private-key: ${{ secrets.GATE_APP_PRIVATE_KEY }}",
    "",
    "      - name: Auto-approve as gate bot",
    "        if: success() && steps.classify.outputs.classification != 'cross_owner'",
    "        env:",
    "          GH_TOKEN: ${{ steps.app-token.outputs.token }}",
    "          PR: ${{ github.event.pull_request.number }}",
    "          HEAD_SHA: ${{ github.event.pull_request.head.sha }}",
    "          REPO: ${{ github.repository }}",
    "          CLASSIFICATION: ${{ steps.classify.outputs.classification }}",
    "          REASON: ${{ steps.classify.outputs.reason }}",
    "        run: |",
    "          set -e",
    '          existing=$(gh api "repos/$REPO/pulls/$PR/reviews" \\',
    '            --jq "[.[] | select(.user.type == \\"Bot\\" and .commit_id == \\"$HEAD_SHA\\" and .state == \\"APPROVED\\")] | length")',
    '          if [ "$existing" -gt 0 ]; then',
    '            echo "Bot already approved $HEAD_SHA; skipping."',
    "            exit 0",
    "          fi",
    '          gh pr review "$PR" --repo "$REPO" --approve \\',
    '            --body "Auto-approved by gate: $CLASSIFICATION - $REASON"',
    "",
    "      # GITHUB_TOKEN cannot call enablePullRequestAutoMerge in this org",
    '      # ("Resource not accessible by integration"), so reuse the gate App\'s',
    "      # installation token. Skipped for cross_owner PRs - those land via a",
    "      # human owner merging after review.",
    "      - name: Enable auto-merge (best-effort)",
    "        if: success() && steps.classify.outputs.classification != 'cross_owner'",
    "        uses: actions/github-script@v7",
    "        continue-on-error: true",
    "        with:",
    "          github-token: ${{ steps.app-token.outputs.token }}",
    "          script: |",
    "            try {",
    "              await github.graphql(",
    "                `mutation EnableAutoMerge($pullRequestId: ID!) {",
    "                  enablePullRequestAutoMerge(input: {",
    "                    pullRequestId: $pullRequestId,",
    "                    mergeMethod: SQUASH,",
    "                  }) {",
    "                    pullRequest { number }",
    "                  }",
    "                }`,",
    "                { pullRequestId: context.payload.pull_request.node_id },",
    "              );",
    "              core.info('Auto-merge enabled.');",
    "            } catch (e) {",
    "              core.warning(`Auto-merge could not be enabled (PR can still be merged manually): ${e.message}`);",
    "            }",
  ].join("\n");
}

export function renderReviewEnforcerWorkflow(): string {
  return [
    "# first-tree-template-version: 1",
    "name: Cross-owner review enforcer",
    "",
    "# Companion workflow to auto-merge.yml for the strict cross_owner enforcement.",
    "# Ruleset requires 1 approving review (any write member can satisfy), so",
    "# without enforcement a random non-owner could approve a cross_owner PR.",
    "# This workflow runs on each submitted APPROVED review, re-classifies the PR,",
    "# and dismisses the review if the reviewer is not in the file's frontmatter",
    "# `owners` (or in the [*] expansion).",
    "",
    "on:",
    "  pull_request_review:",
    "    types: [submitted]",
    "",
    "permissions:",
    "  contents: read",
    "  pull-requests: write  # for dismissing reviews",
    "",
    "jobs:",
    "  enforce:",
    "    if: github.event.review.state == 'approved'",
    "    runs-on: ubuntu-latest",
    "    steps:",
    "      - uses: actions/checkout@v4",
    "        with:",
    "          ref: ${{ github.event.pull_request.base.sha }}",
    "          fetch-depth: 0",
    "",
    "      - name: Classify PR + dismiss non-owner approval",
    "        uses: actions/github-script@v7",
    "        with:",
    "          script: |",
    "            const fs = require('fs');",
    "            const { execFileSync } = require('child_process');",
    "",
    "            const pr = context.payload.pull_request;",
    "            const review = context.payload.review;",
    "            const author = pr.user.login;",
    "            const reviewer = review.user.login;",
    "            const baseSha = pr.base.sha;",
    "",
    "            // Skip self-reviews defensively (GitHub disallows but cheap to check).",
    "            if (reviewer === author) {",
    "              core.info(`Reviewer ${reviewer} is PR author; skipping.`);",
    "              return;",
    "            }",
    "",
    "            // ---- Collect changed files ----",
    "            const files = await github.paginate(github.rest.pulls.listFiles, {",
    "              owner: context.repo.owner,",
    "              repo: context.repo.repo,",
    "              pull_number: pr.number,",
    "              per_page: 100,",
    "            });",
    "",
    "            // ---- Personal-path short-circuit (members/<author>/**) ----",
    "            const personalPrefix = `members/${author}/`;",
    "            const allPersonal = files.length > 0 &&",
    "              files.every((f) => f.filename.startsWith(personalPrefix));",
    "            if (allPersonal) {",
    "              core.info('Personal PR; reviewer enforcement does not apply.');",
    "              return;",
    "            }",
    "",
    "            // ---- All-members list for [*] expansion ----",
    "            function parseInlineOwners(content) {",
    "              const fmMatch = content.match(/^---\\s*\\n([\\s\\S]*?)\\n---/);",
    "              if (!fmMatch) return null;",
    "              const fm = fmMatch[1];",
    "              const inline = fm.match(/^owners:\\s*\\[([^\\]]*)\\]/m);",
    "              if (inline) {",
    "                const raw = inline[1].trim();",
    "                if (!raw || raw === '*') return null;",
    "                return raw",
    "                  .split(',')",
    "                  .map((s) => s.trim().replace(/^['\"]|['\"]$/g, ''))",
    "                  .filter(Boolean);",
    "              }",
    "              const block = fm.match(/^owners:\\s*\\n((?:\\s+-\\s+.+\\n?)+)/m);",
    "              if (block) {",
    "                return block[1]",
    "                  .trim()",
    "                  .split('\\n')",
    "                  .map((line) =>",
    "                    line.replace(/#.*$/, '').trim().replace(/^-\\s*/, '').trim().replace(/^['\"]|['\"]$/g, ''),",
    "                  )",
    "                  .filter(Boolean);",
    "              }",
    "              return null;",
    "            }",
    "",
    "            const allMembers = fs.readdirSync('members', { withFileTypes: true })",
    "              .filter((e) => e.isDirectory())",
    "              .flatMap((e) => {",
    "                try {",
    "                  const content = fs.readFileSync(`members/${e.name}/NODE.md`, 'utf-8');",
    "                  const owners = parseInlineOwners(content);",
    "                  if (owners && owners.length > 0) return owners;",
    "                } catch {",
    "                  // Fall through.",
    "                }",
    "                return [e.name];",
    "              });",
    "",
    "            // ---- Build owner intersection across changed files ----",
    "            function readBaseContent(path) {",
    "              try {",
    "                return execFileSync('git', ['show', `${baseSha}:${path}`], { encoding: 'utf-8' });",
    "              } catch {",
    "                return null;",
    "              }",
    "            }",
    "",
    "            function parseOwnersField(content) {",
    "              const fmMatch = content.match(/^---\\s*\\n([\\s\\S]*?)\\n---/);",
    "              if (!fmMatch) return null;",
    "              const fm = fmMatch[1];",
    "              const inline = fm.match(/^owners:\\s*\\[([^\\]]*)\\]/m);",
    "              if (inline) {",
    "                const raw = inline[1].trim();",
    "                if (raw === '*') return [...allMembers];",
    "                if (!raw) return null;",
    "                return raw",
    "                  .split(',')",
    "                  .map((s) => s.trim().replace(/^['\"]|['\"]$/g, ''))",
    "                  .filter(Boolean);",
    "              }",
    "              const block = fm.match(/^owners:\\s*\\n((?:\\s+-\\s+.+\\n?)+)/m);",
    "              if (block) {",
    "                return block[1]",
    "                  .trim()",
    "                  .split('\\n')",
    "                  .map((line) =>",
    "                    line.replace(/#.*$/, '').trim().replace(/^-\\s*/, '').trim().replace(/^['\"]|['\"]$/g, ''),",
    "                  )",
    "                  .filter(Boolean);",
    "              }",
    "              return null;",
    "            }",
    "",
    "            const ownerSets = [];",
    "            for (const file of files) {",
    "              if (!file.filename.endsWith('.md') || file.status === 'renamed' ||",
    "                  (file.status === 'added' && !file.filename.startsWith('members/'))) {",
    "                ownerSets.push(allMembers); // restrictive fallback",
    "                continue;",
    "              }",
    "              const personalMatch = file.filename.match(/^members\\/([^/]+)\\//);",
    "              if (personalMatch) {",
    "                ownerSets.push([personalMatch[1]]);",
    "                continue;",
    "              }",
    "              const content = readBaseContent(file.filename);",
    "              if (content === null) {",
    "                ownerSets.push(allMembers);",
    "                continue;",
    "              }",
    "              const owners = parseOwnersField(content);",
    "              ownerSets.push(owners && owners.length > 0 ? owners : allMembers);",
    "            }",
    "",
    "            if (ownerSets.length === 0) {",
    "              core.info('No changed files; nothing to enforce.');",
    "              return;",
    "            }",
    "",
    "            let intersection = ownerSets[0];",
    "            for (let i = 1; i < ownerSets.length; i++) {",
    "              intersection = intersection.filter((o) => ownerSets[i].includes(o));",
    "            }",
    "",
    "            // ---- self_owner / [*] short-circuit ----",
    "            if (intersection.includes(author)) {",
    "              core.info(",
    "                `PR is self_owner / [*] (author ${author} in intersection); ` +",
    "                `reviewer enforcement does not apply.`",
    "              );",
    "              return;",
    "            }",
    "",
    "            // ---- cross_owner: enforce reviewer in intersection ----",
    "            if (intersection.includes(reviewer)) {",
    "              core.info(",
    "                `Cross-owner PR approved by listed owner ${reviewer}; allowed.`",
    "              );",
    "              return;",
    "            }",
    "",
    "            core.warning(",
    "              `Reviewer ${reviewer} is NOT in the cross_owner intersection ` +",
    "              `[${intersection.join(', ')}]; dismissing approval.`",
    "            );",
    "",
    "            await github.rest.pulls.dismissReview({",
    "              owner: context.repo.owner,",
    "              repo: context.repo.repo,",
    "              pull_number: pr.number,",
    "              review_id: review.id,",
    "              message:",
    "                `Auto-dismissed: cross-owner PRs require approval from a ` +",
    "                `frontmatter-listed owner. Eligible: ${intersection.join(', ')}.`",
    "            });",
  ].join("\n");
}

export function renderTreeAgentsInstructions(): string {
  return [
    "<!-- BEGIN CONTEXT-TREE FRAMEWORK — do not edit this section -->",
    "# Agent Instructions for Context Tree",
    "",
    "You are working in a **Context Tree** — the living source of truth for decisions across the organization. Read and follow this before doing anything.",
    "",
    "## Principles",
    "",
    "1. **Source of truth for decisions, not execution.** The tree captures the *what* and *why* — strategic choices, cross-domain relationships, constraints. Execution details stay in source systems.",
    "2. **Agents are first-class participants.** The tree is designed to be navigated and updated by agents, not just humans.",
    "3. **Transparency by default.** All information is readable by everyone. Writing requires owner approval; reading is open.",
    "4. **Git-native tree structure.** Each node is a file; each domain is a directory.",
    "",
    "## Before Every Task",
    "",
    "1. Read the root NODE.md to understand the domain map.",
    "2. Read the NODE.md of every domain relevant to your task.",
    "3. Follow soft_links and read the linked nodes too.",
    "4. Read relevant leaf nodes before making cross-domain decisions.",
    "",
    "## During the Task",
    "",
    "- Decide in the tree, execute in source systems.",
    "- Keep execution detail in code repos and runtime systems.",
    "- Respect ownership fields in node frontmatter.",
    "",
    "## After Every Task",
    "",
    "- If you suspect the task changed decisions, constraints, rationale, ownership, or shared workspace relationships, raise a Need-Human-Attention request (`first-tree attention raise --requires-response`) to confirm whether the tree needs updating before opening any code PR. A tree PR is shared-state and externally visible, so the decision needs human endorsement when it is not obvious. See `.claude/skills/attention/SKILL.md` for body shape and waiting behaviour.",
    "- If the attention confirms a tree update is needed (or the change is obviously tree-relevant), open the tree PR first, then the source/workspace code PR.",
    "- If the task changed only implementation details, skip both the attention and the tree PR — open only the source/workspace code PR.",
    "",
    "<!-- END CONTEXT-TREE FRAMEWORK -->",
    "",
    "# Project-Specific Instructions",
    "",
    "<!-- Add your project-specific agent instructions below this line. -->",
    "",
  ].join("\n");
}

export function renderTreeProgress(): string {
  return [
    "# Progress",
    "",
    "- [x] Bootstrap the tree scaffolding",
    "- [x] Install first-tree skills and baseline instructions",
    "- [x] Scaffold default agent templates and org config",
    "",
  ].join("\n");
}
