export {
  CONTENT_SCOPE_LOCK_PREFIX,
  type ContentBarrierOptions,
  ContentDatabaseRegistry,
  type ContentDatabaseSpec,
  ContentOperation,
  ContentPurgeOperation,
  ContentScopeBarrier,
  deleteDatabaseBarrier,
  type SessionLockManager,
  type SessionLockMode,
  type SessionLockOptions,
} from "./content-barrier.js";
export {
  AUTH_COORDINATOR_DATABASE_NAME,
  type AuthorityCursor,
  AuthSessionCoordinator,
  type CoordinatorOptions,
  type CoordinatorPlanner,
  closeCoordinatorConnections,
  keepCoordinatorSnapshot,
  type RetirementResult,
  replaceCoordinatorSnapshot,
} from "./coordinator.js";
export { SessionError, type SessionErrorCode, sessionErrorCodes, toSessionError } from "./errors.js";
export {
  LEGACY_DATABASE_NAMES,
  LEGACY_LOCAL_STORAGE_KEYS,
  LEGACY_LOCAL_STORAGE_PREFIXES,
  LEGACY_SESSION_STORAGE_KEYS,
  LEGACY_SESSION_STORAGE_PREFIXES,
  type LegacyScrubOptions,
  type LegacyScrubResult,
  type LegacyStorageAreas,
  type LegacyStorageScrubResult,
  type StorageArea,
  scrubLegacyDatabases,
  scrubLegacyPersistence,
  scrubLegacyWebStorage,
} from "./legacy-scrub.js";
export { installSessionLifecycleHooks, type SessionLifecycleOptions } from "./lifecycle.js";
export {
  type AccountScope,
  createAccountScopeKey,
  createScopedDatabaseName,
  isDatabaseNameForScope,
  parseAccountScopeKey,
} from "./scope.js";
export {
  type ActivationCertificate,
  type ActivationCertificateInput,
  type ActiveAuthority,
  type AnonymousAuthority,
  AUTHORITY_SCHEMA_VERSION,
  type AuthAuthority,
  type AuthorityPhase,
  type CoordinatorSnapshot,
  type CredentialRecord,
  type CredentialRecordInput,
  createActivationCertificate,
  createCredentialRecord,
  createSessionAttempt,
  createTransitionPermit,
  createViewLease,
  type JsonPrimitive,
  type JsonValue,
  type RetirementCause,
  type RetiringAuthority,
  type SessionAttempt,
  type SessionAttemptInput,
  sameActivation,
  type TransitionAuthority,
  type TransitionPermit,
  type TransitionPermitInput,
  type ViewLease,
  type ViewLeaseInput,
  validateActivationCertificate,
  validateAuthAuthority,
  validateCoordinatorSnapshot,
  validateCredentialRecord,
  validateSessionAttempt,
  validateTransitionPermit,
  validateViewLease,
} from "./types.js";
