import { type ChildProcess, spawn } from "node:child_process";
import { appendFileSync, existsSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { defaultHome } from "@first-tree/shared/config";
import { channelConfig } from "../channel.js";
import { resolveCliInvocation } from "./shared.js";
import type { ResolvedBinary } from "./types.js";

type ChildExit = {
  code: number | null;
  signal: NodeJS.Signals | null;
  error?: Error;
};

type SupervisorSpawn = typeof spawn;
type ResolveInvocation = () => ResolvedBinary;

export type WindowsSupervisorLoopOptions = {
  invocation?: ResolvedBinary;
  resolveInvocation?: ResolveInvocation;
  platform?: NodeJS.Platform;
  spawnProcess?: SupervisorSpawn;
  sleep?: (ms: number) => Promise<void>;
  maxCycles?: number;
};

const CRASH_BACKOFF_MS = [1_000, 2_000, 5_000, 10_000, 30_000, 60_000] as const;
const SELF_RESTART_EXIT_CODE = 75;

export function windowsTaskLeafName(): string {
  return channelConfig.launchdLabel;
}

export function windowsTaskPath(): string {
  return "\\FirstTree\\";
}

export function windowsTaskName(): string {
  return `${windowsTaskPath()}${windowsTaskLeafName()}`;
}

export function windowsSupervisorServiceDir(): string {
  return join(defaultHome(), "service");
}

export function windowsSupervisorWrapperPath(): string {
  return join(windowsSupervisorServiceDir(), `${channelConfig.launchdLabel}-supervisor.cmd`);
}

export function windowsTaskXmlPath(): string {
  return join(windowsSupervisorServiceDir(), `${channelConfig.launchdLabel}-task.xml`);
}

export function windowsSupervisorStopIntentPath(): string {
  return join(defaultHome(), "state", "windows-supervisor-stop.json");
}

export function windowsSupervisorLogPath(): string {
  return join(defaultHome(), "logs", "supervisor.log");
}

export function writeWindowsSupervisorStopIntent(): void {
  const path = windowsSupervisorStopIntentPath();
  mkdirSync(dirname(path), { recursive: true, mode: 0o700 });
  writeFileSync(
    path,
    `${JSON.stringify({ version: 1, requestedAt: new Date().toISOString(), reason: "daemon stop" })}\n`,
    { mode: 0o600 },
  );
}

export function clearWindowsSupervisorStopIntent(): void {
  rmSync(windowsSupervisorStopIntentPath(), { force: true });
}

export function hasWindowsSupervisorStopIntent(): boolean {
  return existsSync(windowsSupervisorStopIntentPath());
}

export function consumeWindowsSupervisorStopIntent(): boolean {
  if (!hasWindowsSupervisorStopIntent()) return false;
  clearWindowsSupervisorStopIntent();
  return true;
}

export function appendWindowsSupervisorLog(message: string): void {
  const path = windowsSupervisorLogPath();
  mkdirSync(dirname(path), { recursive: true, mode: 0o700 });
  appendFileSync(path, `${new Date().toISOString()} ${message.replace(/\n$/u, "")}\n`, { mode: 0o600 });
}

function cmdSetValue(value: string): string {
  return value.replace(/%/g, "%%");
}

function cmdQuote(value: string): string {
  return `"${cmdSetValue(value).replace(/"/g, '""')}"`;
}

export function renderWindowsSupervisorCmd(invocation: ResolvedBinary): string {
  const command =
    invocation.kind === "bin"
      ? [invocation.program, "daemon", "supervise"]
      : [invocation.program, ...invocation.args, "daemon", "supervise"];
  const logDir = dirname(windowsSupervisorLogPath());
  return `@echo off\r
setlocal\r
REM Launcher for the First Tree Windows Task Scheduler supervisor.\r
REM Generated by the CLI on install/refresh -- do not edit.\r
set "FIRST_TREE_HOME=${cmdSetValue(defaultHome())}"\r
if not exist ${cmdQuote(logDir)} mkdir ${cmdQuote(logDir)}\r
${command.map(cmdQuote).join(" ")} >>${cmdQuote(windowsSupervisorLogPath())} 2>&1\r
exit /b %ERRORLEVEL%\r
`;
}

function childArgs(invocation: ResolvedBinary): string[] {
  const args = ["daemon", "start", "--no-interactive"];
  return invocation.kind === "bin" ? args : [...invocation.args, ...args];
}

function childProgram(invocation: ResolvedBinary): string {
  return invocation.program;
}

function isWindowsCommandShim(program: string): boolean {
  return /\.(?:cmd|bat)$/iu.test(program);
}

function childSpawnTarget(invocation: ResolvedBinary): { program: string; args: string[]; display: string } {
  const program = childProgram(invocation);
  const args = childArgs(invocation);
  const display = [program, ...args].join(" ");
  if (!isWindowsCommandShim(program)) return { program, args, display };

  const commandLine = [program, ...args].map(cmdQuote).join(" ");
  return {
    program: process.env.ComSpec || "cmd.exe",
    args: ["/d", "/s", "/c", `"${commandLine}"`],
    display,
  };
}

function normalizeExitCode(code: number | null, signal: NodeJS.Signals | null): string {
  if (code !== null) return String(code);
  return signal ? `signal ${signal}` : "unknown";
}

function waitForChild(child: ChildProcess): Promise<ChildExit> {
  return new Promise((resolve) => {
    let settled = false;
    const finish = (result: ChildExit): void => {
      if (settled) return;
      settled = true;
      child.off("exit", onExit);
      child.off("error", onError);
      resolve(result);
    };
    const onExit = (code: number | null, signal: NodeJS.Signals | null): void => {
      finish({ code, signal });
    };
    const onError = (error: Error): void => {
      finish({ code: null, signal: null, error });
    };
    child.once("exit", onExit);
    child.once("error", onError);
  });
}

function defaultSleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function pipeChildOutput(child: ChildProcess): void {
  child.stdout?.on("data", (chunk: Buffer | string) => {
    const text = String(chunk).trimEnd();
    if (text) appendWindowsSupervisorLog(`[child stdout] ${text}`);
  });
  child.stderr?.on("data", (chunk: Buffer | string) => {
    const text = String(chunk).trimEnd();
    if (text) appendWindowsSupervisorLog(`[child stderr] ${text}`);
  });
}

function errorMessage(err: unknown): string {
  return err instanceof Error ? err.message : String(err);
}

function childBackoffMs(crashCount: number): number {
  return CRASH_BACKOFF_MS[Math.min(crashCount, CRASH_BACKOFF_MS.length - 1)];
}

export async function runWindowsSupervisorLoop(options: WindowsSupervisorLoopOptions = {}): Promise<number> {
  const platform = options.platform ?? process.platform;
  if (platform !== "win32") {
    throw new Error(`Windows supervisor loop is only supported on win32 (current platform: ${platform}).`);
  }

  const spawnProcess = options.spawnProcess ?? spawn;
  const sleep = options.sleep ?? defaultSleep;
  const resolveInvocation = options.resolveInvocation ?? (() => options.invocation ?? resolveCliInvocation());
  const maxCycles = options.maxCycles ?? Number.POSITIVE_INFINITY;
  let crashCount = 0;
  let cycle = 0;

  appendWindowsSupervisorLog(`supervisor starting for task ${windowsTaskName()}`);

  while (cycle < maxCycles) {
    cycle += 1;
    if (consumeWindowsSupervisorStopIntent()) {
      appendWindowsSupervisorLog("stop intent consumed before child start; supervisor exiting");
      return 0;
    }

    let invocation: ResolvedBinary;
    try {
      invocation = resolveInvocation();
    } catch (err) {
      const backoff = childBackoffMs(crashCount);
      crashCount += 1;
      appendWindowsSupervisorLog(`failed to resolve daemon child invocation: ${errorMessage(err)}`);
      appendWindowsSupervisorLog(`daemon child failed; restarting after ${backoff}ms`);
      await sleep(backoff);
      continue;
    }

    const target = childSpawnTarget(invocation);
    appendWindowsSupervisorLog(`starting daemon child: ${target.display}`);
    let child: ChildProcess;
    try {
      child = spawnProcess(target.program, target.args, {
        detached: false,
        env: {
          ...process.env,
          FIRST_TREE_HOME: defaultHome(),
          FIRST_TREE_SERVICE_MODE: "1",
        },
        stdio: ["ignore", "pipe", "pipe"],
        windowsHide: true,
      });
    } catch (err) {
      const backoff = childBackoffMs(crashCount);
      crashCount += 1;
      appendWindowsSupervisorLog(`failed to spawn daemon child: ${errorMessage(err)}`);
      appendWindowsSupervisorLog(`daemon child failed; restarting after ${backoff}ms`);
      await sleep(backoff);
      continue;
    }
    appendWindowsSupervisorLog(`daemon child started${child.pid ? ` pid=${child.pid}` : ""}`);
    const childResult = waitForChild(child);
    pipeChildOutput(child);

    const { code, signal, error } = await childResult;
    if (error) {
      appendWindowsSupervisorLog(`daemon child spawn error: ${errorMessage(error)}`);
      if (consumeWindowsSupervisorStopIntent()) {
        appendWindowsSupervisorLog("stop intent consumed after child spawn error; supervisor exiting");
        return 0;
      }
      const backoff = childBackoffMs(crashCount);
      crashCount += 1;
      appendWindowsSupervisorLog(`daemon child failed; restarting after ${backoff}ms`);
      await sleep(backoff);
      continue;
    }
    const exitText = normalizeExitCode(code, signal);
    appendWindowsSupervisorLog(`daemon child exited with ${exitText}`);

    if (consumeWindowsSupervisorStopIntent()) {
      appendWindowsSupervisorLog("stop intent consumed after child exit; supervisor exiting");
      return 0;
    }

    if (code === 0) {
      appendWindowsSupervisorLog("daemon child exited cleanly; supervisor exiting");
      return 0;
    }

    if (code === SELF_RESTART_EXIT_CODE) {
      crashCount = 0;
      appendWindowsSupervisorLog(`daemon child requested self-update restart (${SELF_RESTART_EXIT_CODE})`);
      continue;
    }

    const backoff = childBackoffMs(crashCount);
    crashCount += 1;
    appendWindowsSupervisorLog(`daemon child failed; restarting after ${backoff}ms`);
    await sleep(backoff);
  }

  appendWindowsSupervisorLog(`supervisor cycle limit ${maxCycles} reached; exiting`);
  return 1;
}
