export type { ServiceInfo, ServiceOpResult, ServiceState } from "./supervisor/index.js";
export {
  getClientServiceStatus,
  installClientService,
  isServiceSupported,
  isServiceUnitDriftDetected,
  refreshClientServiceUnitForUpdate,
  renderLaunchdWrapper,
  renderPlist,
  renderSystemdUnit,
  renderWindowsSupervisorCmd,
  renderWindowsTaskXml,
  resolveCliInvocation,
  restartClientService,
  startClientService,
  stopClientService,
  uninstallClientService,
  windowsSupervisorLogPath,
  windowsSupervisorWrapperLogPath,
  windowsSupervisorWrapperPath,
  windowsTaskName,
  windowsTaskXmlPath,
} from "./supervisor/index.js";
