// Schemas

// -- Assembled-briefing copy guard (shared by server validation and CLI prompt writes) --
export {
  AGENT_BRIEFING_GENERATED_MARKER,
  type BriefingFingerprint,
  findAssembledBriefingFingerprint,
} from "./agent-briefing-guard.js";
export { canonicalGitRepoUrl } from "./canonical-git-repo-url.js";
// -- Document review (docloop) anchor building / locating --
export {
  type BuildDocAnchorInput,
  buildDocAnchor,
  type DocAnchorRange,
  locateDocAnchor,
  locateDocAnchors,
} from "./doc-anchor.js";
export {
  DISPLAY_NAME_MAX_LENGTH,
  type ExternalAccountProfile,
  githubExternalProfile,
  googleExternalProfile,
  normalizeExternalProfile,
  normalizeUsername,
  USERNAME_BASE_MAX_LENGTH,
  USERNAME_MAX_LENGTH,
  USERNAME_SUFFIX_RESERVE,
} from "./external-account.js";
// -- Mention extraction (shared by the server fan-out resolver and other readers) --
export { type BarePathMatch, scanBareDocPathTokens, stripDocPathLineSuffix } from "./lib/doc-link-scan.js";
export {
  buildWorkspaceDocKey,
  isCanonicalDocLinkPath,
  looksLikeChatId,
  normalizeDocLinkPath,
  parseWorkspaceDocKey,
} from "./lib/doc-path.js";
// -- GitHub-style identicon avatar generator (shared by web Avatar fallback; pure, browser + Node safe) --
export { type IdenticonSvgOptions, identiconCells, identiconSvg } from "./lib/identicon.js";
export {
  extractMentions,
  MENTION_REGEX,
  type MentionParticipant,
  type MentionSegment,
  scanMentionTokens,
  segmentMentions,
  stripCode,
} from "./mentions.js";
// -- OAuth-callback open-redirect guard --
export { DEFAULT_SAFE_REDIRECT, safeRedirectPath } from "./safe-redirect.js";
export {
  type ActiveRuntimeChatIdsResponse,
  activeRuntimeChatIdsResponseSchema,
} from "./schemas/active-runtime-chats.js";
export {
  AGENT_NAME_MAX_LENGTH,
  AGENT_NAME_REGEX,
  AGENT_SOURCES,
  AGENT_STATUSES,
  AGENT_TYPES,
  AGENT_VISIBILITY,
  type Agent,
  type AgentPinnedMessage,
  type AgentSource,
  type AgentStatus,
  type AgentType,
  type AgentVisibility,
  AVATAR_COLOR_TOKENS,
  type AvatarColorToken,
  agentPinnedMessageSchema,
  agentSchema,
  agentSourceSchema,
  agentStatusSchema,
  agentTypeSchema,
  agentVisibilitySchema,
  avatarColorTokenSchema,
  type ContextTreeInfo,
  type CreateAgent,
  contextTreeInfoSchema,
  createAgentSchema,
  findReservedAgentMetadataKey,
  isReservedAgentName,
  type LegacyWireAgentType,
  type ListAgentsQuery,
  legacyWireAgentTypeSchema,
  listAgentsQuerySchema,
  type NewChatDefaultCandidateAgent,
  type NewChatDefaultCandidatesRequest,
  type NewChatDefaultCandidatesResponse,
  newChatDefaultCandidateAgentSchema,
  newChatDefaultCandidatesRequestSchema,
  newChatDefaultCandidatesResponseSchema,
  RESERVED_AGENT_METADATA_KEYS,
  RESERVED_AGENT_NAMES,
  type SwitchAgentRuntime,
  switchAgentRuntimeSchema,
  type UpdateAgent,
  updateAgentSchema,
  userAgentMetadataSchema,
} from "./schemas/agent.js";
export {
  type AgentRuntimeConfig,
  type AgentRuntimeConfigDryRunResult,
  type AgentRuntimeConfigPatch,
  type AgentRuntimeConfigPayload,
  agentRuntimeConfigDryRunResultSchema,
  agentRuntimeConfigPayloadSchema,
  agentRuntimeConfigSchema,
  type ClientMessagePayload,
  DEFAULT_AGENT_RUNTIME_CONFIG_PAYLOAD,
  DEFAULT_CLAUDE_CODE_TUI_RUNTIME_CONFIG_PAYLOAD,
  DEFAULT_CODEX_RUNTIME_CONFIG_PAYLOAD,
  DEFAULT_CURSOR_RUNTIME_CONFIG_PAYLOAD,
  DEFAULT_KIMI_CODE_RUNTIME_CONFIG_PAYLOAD,
  type DryRunAgentRuntimeConfig,
  defaultRuntimeConfigPayload,
  deriveRepoLocalPath,
  deriveRepoShortLabel,
  dryRunAgentRuntimeConfigSchema,
  ENV_REDACTED_PLACEHOLDER,
  type EnvEntry,
  envEntrySchema,
  formatRepoCoordinate,
  type GitRepo,
  getRepoLocalPathSafetyError,
  gitRepoSchema,
  isRedactedEnvValue,
  isSafeRepoLocalPath,
  type McpHttpServer,
  type McpServer,
  type McpSseServer,
  type McpStdioServer,
  mcpServerSchema,
  normalizeRepoLocalPath,
  PROMPT_APPEND_MAX_LENGTH,
  type PromptConfig,
  type PromptSection,
  type PromptSectionScope,
  promptConfigSchema,
  promptSectionSchema,
  promptSectionScopeSchema,
  type RuntimeResourceSkill,
  runtimeResourceSkillSchema,
  type UpdateAgentRuntimeConfig,
  updateAgentRuntimeConfigSchema,
} from "./schemas/agent-runtime-config.js";
export {
  AGENT_ENGAGEMENTS,
  AGENT_MAIN_STATUSES,
  type AgentChatStatus,
  type AgentChatStatusInput,
  type AgentEngagement,
  type AgentMainStatus,
  agentChatStatusSchema,
  agentEngagementSchema,
  agentMainStatusSchema,
  buildAgentChatStatus,
  compareMainStatus,
  type DeriveMainStatusInput,
  deriveMainStatus,
  MAIN_STATUS_PRIORITY,
  RUNTIME_STALE_MS,
} from "./schemas/agent-status.js";
export {
  ATTACHMENT_FILENAME_HEADER,
  ATTACHMENT_MIME_HEADER,
  type AttachmentMetadata,
  attachmentMetadataSchema,
  MAX_ATTACHMENT_BYTES,
  type UploadAttachmentResponse,
  uploadAttachmentResponseSchema,
} from "./schemas/attachment.js";
export {
  COMPOSER_ACCEPT_ATTRIBUTE,
  classifyComposerUpload,
  OFFICE_EXTENSIONS,
  OFFICE_MIME_TO_EXTENSION,
  TEXT_NATIVE_EXTENSIONS,
  type UploadClassification,
} from "./schemas/attachment-classification.js";
export {
  ATTACHMENT_KINDS,
  type AttachmentKind,
  type AttachmentRef,
  attachmentKindSchema,
  attachmentRefSchema,
  attachmentRefsFromMetadata,
  isAttachmentRef,
  MAX_MESSAGE_ATTACHMENT_REFS,
} from "./schemas/attachment-ref.js";
export {
  type ConnectTokenExchange,
  type ConnectTokenResponse,
  connectTokenExchangeSchema,
  connectTokenResponseSchema,
  type Login,
  type LoginResponse,
  loginResponseSchema,
  loginSchema,
  type RefreshToken,
  refreshTokenSchema,
} from "./schemas/auth.js";
export {
  type AddParticipant,
  addParticipantSchema,
  CHAT_ENGAGEMENT_STATUSES,
  CHAT_TYPES,
  type Chat,
  type ChatDetail,
  type ChatEngagementStatus,
  type ChatParticipant,
  type ChatParticipantDetail,
  type ChatType,
  type CreateChat,
  type CreateTaskChat,
  type CreateWebTaskChat,
  chatDetailSchema,
  chatEngagementStatusSchema,
  chatParticipantDetailSchema,
  chatParticipantSchema,
  chatSchema,
  chatTypeSchema,
  createChatSchema,
  createTaskChatSchema,
  createWebTaskChatSchema,
  type LegacyCreateChat,
  legacyCreateChatSchema,
  type PatchChatEngagement,
  patchChatEngagementSchema,
  type RemoveParticipant,
  removeParticipantSchema,
  type UpdateChat,
  updateChatSchema,
} from "./schemas/chat.js";
export {
  type ChatGithubEntity,
  type ChatGithubEntityListResponse,
  chatGithubEntityListResponseSchema,
  chatGithubEntitySchema,
  DECLARED_BOUND_VIA,
  type DeclaredBoundVia,
  type FollowGithubEntityConflict,
  type FollowGithubEntityRequest,
  type FollowGithubEntityResponse,
  followGithubEntityConflictSchema,
  followGithubEntityRequestSchema,
  followGithubEntityResponseSchema,
  type GithubEntityBoundVia,
  type GithubEntityLiveState,
  githubEntityBoundViaSchema,
  githubEntityLiveStateSchema,
  isDeclaredBoundVia,
  type UnfollowGithubEntityResponse,
  unfollowGithubEntityResponseSchema,
} from "./schemas/chat-github-entities.js";
export {
  type ChatGitlabEntity,
  type ChatGitlabEntityBoundVia,
  type ChatGitlabEntityListResponse,
  type ChatGitlabEntityStatus,
  type ChatGitlabEntityType,
  chatGitlabEntityBoundViaSchema,
  chatGitlabEntityListResponseSchema,
  chatGitlabEntitySchema,
  chatGitlabEntityStatusSchema,
  chatGitlabEntityTypeSchema,
  type FollowChatGitlabEntityConflict,
  type FollowChatGitlabEntityRequest,
  type FollowChatGitlabEntityResponse,
  followChatGitlabEntityConflictSchema,
  followChatGitlabEntityRequestSchema,
  followChatGitlabEntityResponseSchema,
  type UnfollowChatGitlabEntityResponse,
  unfollowChatGitlabEntityResponseSchema,
} from "./schemas/chat-gitlab-entities.js";
export {
  type AgentChatMetadata,
  agentChatMetadataSchema,
  CHAT_SOURCES,
  type ChatMetadata,
  type ChatSource,
  chatMetadataSchema,
  chatSourceSchema,
  GITHUB_ENTITY_TYPES,
  type GithubChatMetadata,
  type GithubEntityType,
  type GitlabChatMetadata,
  githubChatMetadataSchema,
  githubEntityTypeSchema,
  gitlabChatMetadataSchema,
  type OptionalChatMetadata,
  optionalChatMetadataSchema,
} from "./schemas/chat-metadata.js";
export {
  CLIENT_STATUSES,
  type Client,
  type ClientAuthState,
  type ClientRegister,
  type ClientStatus,
  type ClientWireCapabilities,
  clientAuthStateSchema,
  clientRegisterSchema,
  clientSchema,
  clientStatusSchema,
  clientWireCapabilitiesSchema,
  type UpdateAttempt,
  updateAttemptSchema,
} from "./schemas/client.js";
export {
  CAPABILITY_STATES,
  type CapabilityAuthMethod,
  type CapabilityEntry,
  type CapabilityRuntimeSource,
  type CapabilityState,
  type ClientCapabilities,
  capabilityAuthMethodSchema,
  capabilityEntrySchema,
  capabilityRuntimeSourceSchema,
  capabilityStateSchema,
  clientCapabilitiesSchema,
  type PendingAuth,
  type PendingAuthMethod,
  pendingAuthMethodSchema,
  pendingAuthSchema,
  type UpdateClientCapabilities,
  updateClientCapabilitiesSchema,
} from "./schemas/client-capabilities.js";
export {
  type PaginationQuery,
  paginatedResponse,
  paginationQuerySchema,
} from "./schemas/common.js";
export {
  CONTEXT_REVIEW_BODY_MAX_BYTES,
  CONTEXT_REVIEW_ERROR_CODES,
  CONTEXT_REVIEW_EVENTS,
  type ContextReviewErrorCode,
  type ContextReviewEvent,
  type ContextReviewSubmitRequest,
  type ContextReviewSubmitResponse,
  contextReviewErrorCodeSchema,
  contextReviewEventSchema,
  contextReviewSubmitRequestSchema,
  contextReviewSubmitResponseSchema,
} from "./schemas/context-review.js";
export {
  CONTEXT_TREE_CHANGE_TYPES,
  CONTEXT_TREE_EDGE_KINDS,
  CONTEXT_TREE_NODE_KINDS,
  CONTEXT_TREE_RISK_LEVELS,
  CONTEXT_TREE_SNAPSHOT_STATUSES,
  CONTEXT_TREE_STATUS_SEVERITIES,
  type ContextTreeChange,
  type ContextTreeChangeType,
  type ContextTreeEdge,
  type ContextTreeEdgeKind,
  type ContextTreeInstallationInfoResponse,
  type ContextTreeIoAction,
  type ContextTreeIoAgentSummary,
  type ContextTreeIoBucket,
  type ContextTreeIoEvent,
  type ContextTreeIoSkipBreakdown,
  type ContextTreeIoSkipReason,
  type ContextTreeIoSkipSummary,
  type ContextTreeIoSource,
  type ContextTreeIoSummary,
  type ContextTreeIoTargetKind,
  type ContextTreeNode,
  type ContextTreeNodeKind,
  type ContextTreeRecoveryAction,
  type ContextTreeRiskLevel,
  type ContextTreeSnapshot,
  type ContextTreeSnapshotStatus,
  type ContextTreeStatus,
  type ContextTreeStatusSeverity,
  type ContextTreeSummary,
  type ContextTreeUpdate,
  type ContextTreeUsageEvent,
  type ContextTreeUsageSummary,
  type ContextTreeWriteEvent,
  contextTreeChangeSchema,
  contextTreeChangeTypeSchema,
  contextTreeEdgeKindSchema,
  contextTreeEdgeSchema,
  contextTreeInstallationInfoResponseSchema,
  contextTreeIoActionSchema,
  contextTreeIoAgentSummarySchema,
  contextTreeIoBucketSchema,
  contextTreeIoEventSchema,
  contextTreeIoSkipBreakdownSchema,
  contextTreeIoSkipReasonSchema,
  contextTreeIoSkipSummarySchema,
  contextTreeIoSourceSchema,
  contextTreeIoSummarySchema,
  contextTreeIoTargetKindSchema,
  contextTreeNodeKindSchema,
  contextTreeNodeSchema,
  contextTreeRecoveryActionSchema,
  contextTreeRiskLevelSchema,
  contextTreeSnapshotSchema,
  contextTreeSnapshotStatusSchema,
  contextTreeStatusSchema,
  contextTreeStatusSeveritySchema,
  contextTreeSummarySchema,
  contextTreeUpdateSchema,
  contextTreeUsageEventSchema,
  contextTreeUsageSummarySchema,
  contextTreeWriteEventSchema,
  type InitializeContextTreeRequest,
  type InitializeContextTreeResponse,
  initializeContextTreeRequestSchema,
  initializeContextTreeResponseSchema,
} from "./schemas/context-tree.js";
// -- Document review (docloop): org document library with versioned publishes and anchored comments --
export {
  type CreateDocCommentRequest,
  createDocCommentRequestSchema,
  DOC_ANCHOR_CONTEXT_MAX,
  DOC_ANCHOR_EXACT_MAX,
  DOC_COMMENT_BODY_MAX,
  DOC_COMMENT_STATUSES,
  DOC_CONTENT_MAX_CHARS,
  DOC_PROJECT_MAX,
  DOC_PUBLISH_BODY_LIMIT,
  DOC_SLUG_MAX,
  DOC_STATUSES,
  DOC_TITLE_MAX,
  DOC_VERSION_NOTE_MAX,
  type DocAnchor,
  type DocAuthor,
  type DocComment,
  type DocCommentStatus,
  type DocStatus,
  type DocSummary,
  type DocVersion,
  type DocWithVersion,
  docAnchorSchema,
  docAuthorSchema,
  docCommentSchema,
  docCommentStatusSchema,
  docSlugSchema,
  docStatusSchema,
  docSummarySchema,
  docVersionSchema,
  docWithVersionSchema,
  type ListDocCommentsQuery,
  type ListDocCommentsResponse,
  type ListDocsQuery,
  type ListDocsResponse,
  listDocCommentsQuerySchema,
  listDocCommentsResponseSchema,
  listDocsQuerySchema,
  listDocsResponseSchema,
  type PublishDocRequest,
  type PublishDocResponse,
  publishDocRequestSchema,
  publishDocResponseSchema,
  type ReplyDocCommentRequest,
  replyDocCommentRequestSchema,
  type UpdateDocCommentRequest,
  type UpdateDocRequest,
  updateDocCommentRequestSchema,
  updateDocRequestSchema,
} from "./schemas/document.js";
export {
  GITHUB_ACCOUNT_TYPES,
  GITHUB_APP_CONNECT_STATUSES,
  GITHUB_PERMISSION_LEVELS,
  type GithubAccountType,
  type GithubAppConnectBody,
  type GithubAppConnectPanelInstallation,
  type GithubAppConnectPanelOutput,
  type GithubAppConnectStatus,
  type GithubAppInstallationEvents,
  type GithubAppInstallationOutput,
  type GithubAppInstallationPermissions,
  type GithubAppUserTokenMetadata,
  type GithubPermissionLevel,
  githubAccountTypeSchema,
  githubAppConnectBodySchema,
  githubAppConnectPanelInstallationSchema,
  githubAppConnectPanelOutputSchema,
  githubAppConnectStatusSchema,
  githubAppInstallationEventsSchema,
  githubAppInstallationOutputSchema,
  githubAppInstallationPermissionsSchema,
  githubAppUserTokenMetadataSchema,
  githubPermissionLevelSchema,
} from "./schemas/github-app.js";
export {
  type FollowGitlabEntity,
  followGitlabEntitySchema,
  GITLAB_IDENTITY_LINK_STATES,
  GITLAB_REVIEWER_MODES,
  type GitlabConnectionCreate,
  type GitlabConnectionSecretResponse,
  type GitlabConnectionSummary,
  type GitlabIdentityLinkCreate,
  type GitlabIdentityLinkState,
  type GitlabIdentityLinkSummary,
  type GitlabReviewerMode,
  type GitlabTargetClass,
  gitlabConnectionCreateSchema,
  gitlabConnectionSecretResponseSchema,
  gitlabConnectionSummarySchema,
  gitlabIdentityLinkCreateSchema,
  gitlabIdentityLinkStateSchema,
  gitlabIdentityLinkSummarySchema,
  gitlabReviewerModeSchema,
  gitlabTargetClassSchema,
} from "./schemas/gitlab.js";
export {
  extractCaption,
  IMAGE_MIME_TO_EXT,
  type ImageBatchRefContent,
  type ImageRefContent,
  imageBatchRefContentSchema,
  imageRefContentSchema,
  isImageBatchRefContent,
  isImageRefContent,
  MAX_BATCH_ATTACHMENTS,
  SUPPORTED_IMAGE_MIMES,
  type SupportedImageMime,
  supportedImageMimeSchema,
} from "./schemas/image-payload.js";
export {
  INBOX_ENTRY_STATUSES,
  type InboxEntry,
  type InboxEntryStatus,
  type InboxEntryWithMessage,
  type InboxPollQuery,
  inboxEntrySchema,
  inboxEntryStatusSchema,
  inboxEntryWithMessageSchema,
  inboxPollQuerySchema,
} from "./schemas/inbox.js";
export type {
  InboxAckAcceptedDisposition,
  InboxAckAcceptedFrame,
  InboxAckFrame,
  InboxAckRejectedFrame,
  InboxAckRejectedReason,
  InboxDeliverFrame,
  InboxRecoverAcceptedFrame,
  InboxRecoverFrame,
  InboxRecoverRejectedFrame,
  InboxRecoverRejectedReason,
} from "./schemas/inbox-frames.js";
// -- WebSocket inbox data-plane frames --
export {
  inboxAckAcceptedDispositionSchema,
  inboxAckAcceptedFrameSchema,
  inboxAckFrameSchema,
  inboxAckRejectedFrameSchema,
  inboxAckRejectedReasonSchema,
  inboxDeliverFrameSchema,
  inboxRecoverAcceptedFrameSchema,
  inboxRecoverFrameSchema,
  inboxRecoverRejectedFrameSchema,
  inboxRecoverRejectedReasonSchema,
} from "./schemas/inbox-frames.js";
export {
  INVITATION_DEFAULT_TTL_DAYS,
  type InvitationPreview,
  type InvitationView,
  invitationPreviewSchema,
  invitationViewSchema,
  type JoinByInvitation,
  joinByInvitationSchema,
  rotateInvitationSchema,
} from "./schemas/invitation.js";
export {
  isKnownLandingCampaignSlug,
  isLandingCampaignTrialAgentMetadata,
  isLandingCampaignTrialChatLocked,
  KNOWN_LANDING_CAMPAIGN_SLUGS,
  type KnownLandingCampaignSlug,
  knownLandingCampaignSlugSchema,
  type LandingCampaignActionContext,
  type LandingCampaignRepoMetadata,
  type LandingCampaignStartRequest,
  type LandingCampaignStartResponse,
  type LandingCampaignTrialAgentMetadata,
  type LandingCampaignTrialAwaitingUserKind,
  type LandingCampaignTrialChatMetadata,
  type LandingCampaignTrialChatState,
  type LandingCampaignTrialLimitReason,
  landingCampaignActionContextSchema,
  landingCampaignRepoMetadataSchema,
  landingCampaignRepoSlugSchema,
  landingCampaignSlugSchema,
  landingCampaignStartRequestSchema,
  landingCampaignStartResponseSchema,
  landingCampaignTrialAgentMetadataSchema,
  landingCampaignTrialAwaitingUserKindSchema,
  landingCampaignTrialChatMetadataSchema,
  landingCampaignTrialChatStateSchema,
  landingCampaignTrialLimitReasonSchema,
  parseLandingCampaignTrialAgentMetadata,
  parseLandingCampaignTrialChatMetadata,
} from "./schemas/landing-campaign.js";
export {
  type AddMeChatParticipants,
  ASSISTANT_TEXT_FULL_MAX,
  ASSISTANT_TEXT_PREVIEW_MAX,
  addMeChatParticipantsSchema,
  CHAT_ENGAGEMENT_VIEWS,
  type ChatEngagementView,
  type ChatMessageFrame,
  type ChatSourceCount,
  type CreateMeChat,
  chatEngagementViewSchema,
  chatMessageFrameSchema,
  chatSourceCountSchema,
  createMeChatSchema,
  LIVE_ACTIVITY_STALE_MS,
  type ListMeChatSourceCountsQuery,
  type ListMeChatsQuery,
  type ListMeChatsResponse,
  type LiveActivity,
  type LiveActivityKind,
  listMeChatSourceCountsQuerySchema,
  listMeChatsQuerySchema,
  listMeChatsResponseSchema,
  liveActivityKindSchema,
  liveActivitySchema,
  ME_CHAT_DEFAULT_LIMIT,
  ME_CHAT_FILTERS,
  ME_CHAT_MAX_LIMIT,
  type MeChatFilter,
  type MeChatLeaveResponse,
  type MeChatMembershipKind,
  type MeChatParticipant,
  type MeChatPinResponse,
  type MeChatPriorityRows,
  type MeChatReadResponse,
  type MeChatRow,
  type MeChatSourceCounts,
  type MeChatUnreadResponse,
  meChatFilterSchema,
  meChatLeaveResponseSchema,
  meChatMembershipKindSchema,
  meChatParticipantSchema,
  meChatPinResponseSchema,
  meChatPriorityRowsSchema,
  meChatReadResponseSchema,
  meChatRowSchema,
  meChatSourceCountsSchema,
  meChatUnreadResponseSchema,
  type PinMeChat,
  pinMeChatSchema,
} from "./schemas/me-chat.js";
export {
  type DocSnapshotFailReason,
  type DocumentContext,
  docSnapshotFailReasonSchema,
  documentContextSchema,
  type FailedDocMention,
  failedDocMentionSchema,
  type GetMeDoc,
  type GetMeDocResponse,
  getMeDocResponseSchema,
  getMeDocSchema,
  MAX_FAILED_DOC_MENTION_RAW_LEN,
  MAX_FAILED_DOC_MENTIONS_PER_MESSAGE,
  type WorkspaceDocRef,
  workspaceDocRefSchema,
} from "./schemas/me-doc.js";
export {
  type CompleteOnboarding,
  type CreateOrgFromMe,
  completeOnboardingSchema,
  createOrgFromMeSchema,
  type KickoffOnboarding,
  type KickoffOnboardingResult,
  kickoffOnboardingResultSchema,
  kickoffOnboardingSchema,
  type MeMembership,
  meMembershipSchema,
  type OnboardingEvent,
  type OnboardingEventName,
  type OnboardingStep,
  type OrgBrief,
  onboardingEventNameSchema,
  onboardingEventSchema,
  onboardingStepSchema,
  orgBriefSchema,
  type PatchOnboarding,
  patchOnboardingSchema,
  type TreeSetupKickoff,
  treeSetupKickoffSchema,
} from "./schemas/me-extras.js";
export {
  type CreateMember,
  createMemberSchema,
  MEMBER_ROLES,
  type Member,
  type MemberCreated,
  type MemberRole,
  memberCreatedSchema,
  memberRoleSchema,
  memberSchema,
  type UpdateMember,
  type UpdateMyProfile,
  updateMemberSchema,
  updateMyProfileSchema,
} from "./schemas/member.js";
export {
  AGENT_FINAL_TEXT_METADATA_KEY,
  type AskOption,
  type AskRequest,
  askOptionSchema,
  askRequestSchema,
  CLI_BODY_ORIGIN_METADATA_KEY,
  CLI_BODY_ORIGINS,
  type CliBodyOrigin,
  type ClientMessage,
  clientMessageSchema,
  isAgentFinalTextMetadata,
  isRuntimeNoticeMetadata,
  MESSAGE_FORMATS,
  MESSAGE_SOURCES,
  type Message,
  type MessageFormat,
  type MessagePurpose,
  type MessageSource,
  messageFormatSchema,
  messagePurposeSchema,
  messageSchema,
  messageSourceSchema,
  type ParticipantMode,
  type PrecedingMessage,
  participantModeSchema,
  precedingMessageSchema,
  type RequestResolution,
  RUNTIME_NOTICE_METADATA_KEY,
  requestResolutionSchema,
  type SendMessage,
  sendMessageSchema,
} from "./schemas/message.js";
export {
  GITHUB_EVENT_CARD_REASONS,
  type GithubEventCard,
  type GithubEventCardReason,
  type GitlabEventCard,
  githubEventCardReasonSchema,
  githubEventCardSchema,
  gitlabEventCardSchema,
  INVOLVE_REASONS,
  type InvolveReason,
  involveReasonSchema,
  NORMALIZED_EVENT_KINDS,
  type NormalizedEventKind,
  type NormalizedScmEvent,
  normalizedEventKindSchema,
  normalizedScmEventSchema,
  normalizeScmEntityState,
  SCM_ENTITY_STATES,
  type ScmEntityObservation,
  type ScmEntityState,
  type ScmNormalizedWebhook,
  scmEntityObservationSchema,
  scmEntityStateSchema,
  scmNormalizedWebhookSchema,
} from "./schemas/normalized-event.js";
export {
  NOTIFICATION_SEVERITIES,
  NOTIFICATION_TYPES,
  type NotificationSeverity,
  type NotificationType,
  notificationSeveritySchema,
  notificationTypeSchema,
} from "./schemas/notification.js";
export {
  AUTH_PROVIDERS,
  type AuthProvider,
  type AuthProviderActionResult,
  type AuthProviderAvailability,
  type AuthProviderConnection,
  type AuthProviderConnectionsResponse,
  authProviderActionResultSchema,
  authProviderAvailabilitySchema,
  authProviderConnectionSchema,
  authProviderConnectionsResponseSchema,
  authProviderParamsSchema,
  type GithubCallbackQuery,
  type GithubDevCallbackQuery,
  type GithubStartQuery,
  type GoogleCallbackQuery,
  githubCallbackQuerySchema,
  githubDevCallbackQuerySchema,
  githubStartQuerySchema,
  googleCallbackQuerySchema,
  OAUTH_ERROR_CODES,
  OAUTH_INTENTS,
  type OAuthErrorCode,
  type OAuthIntent,
  type OAuthStartQuery,
  oauthErrorCodeSchema,
  oauthIntentSchema,
  oauthStartQuerySchema,
} from "./schemas/oauth.js";
export {
  type ContextTreeActiveBinding,
  type ContextTreeSettingState,
  classifyContextTreeSetting,
  contextTreeActiveBindingSchema,
  contextTreeBranchSchema,
  contextTreeRepoSchema,
  isOrgSettingNamespace,
  ORG_SETTINGS_NAMESPACE_KEYS,
  ORG_SETTINGS_NAMESPACES,
  type OrgContextTreeFeaturesInput,
  type OrgContextTreeFeaturesOutput,
  type OrgContextTreeFeaturesStorage,
  type OrgContextTreeInput,
  type OrgContextTreeOutput,
  type OrgContextTreeStorage,
  type OrgSettingInput,
  type OrgSettingNamespace,
  type OrgSettingOutput,
  type OrgSettingReadPolicy,
  type OrgSettingStorage,
  type OrgSourceReposInput,
  type OrgSourceReposOutput,
  type OrgSourceReposStorage,
  orgContextTreeFeaturesInputSchema,
  orgContextTreeFeaturesOutputSchema,
  orgContextTreeFeaturesStorageSchema,
  orgContextTreeFinalizeInputSchema,
  orgContextTreeInputSchema,
  orgContextTreeOutputSchema,
  orgContextTreeStorageSchema,
  orgSettingNamespaceSchema,
  orgSourceReposInputSchema,
  orgSourceReposOutputSchema,
  orgSourceReposStorageSchema,
  repoUrlSchema,
} from "./schemas/org-settings.js";
export {
  type CreateOrganization,
  type CreateOrganizationInput,
  createOrganizationSchema,
  type Organization,
  organizationSchema,
  type UpdateOrganization,
  updateOrganizationSchema,
} from "./schemas/organization.js";
export {
  PORTABLE_PLATFORMS,
  type PortableAsset,
  type PortableChannel,
  type PortableInstallMetadata,
  type PortableInstallMethod,
  type PortableLatest,
  type PortableManifest,
  type PortablePlatform,
  portableAssetSchema,
  portableChannelSchema,
  portableInstallMetadataSchema,
  portableInstallMethodSchema,
  portableLatestSchema,
  portableManifestSchema,
  portablePlatformSchema,
} from "./schemas/portable.js";
export {
  type ActivityOverview,
  AGENT_BIND_REJECT_REASONS,
  AGENT_RUNTIME_SESSION_HEADER,
  AGENT_SELECTOR_HEADER,
  type AgentBindRejectReason,
  type AgentBindRequest,
  type AgentPresence,
  activityOverviewSchema,
  agentBindRejectReasonSchema,
  agentBindRequestSchema,
  agentPresenceSchema,
  CLIENT_PAUSED_REASONS,
  type ClientPausedReason,
  type ClientSessionState,
  clientPausedReasonSchema,
  clientSessionStateSchema,
  PRESENCE_STATUSES,
  type PresenceStatus,
  presenceStatusSchema,
  RUNTIME_STATES,
  type RuntimeState,
  type RuntimeStateMessage,
  runtimeStateMessageSchema,
  runtimeStateSchema,
  SESSION_STATES,
  type SessionRuntimeMessage,
  type SessionState,
  type SessionStateMessage,
  sessionRuntimeMessageSchema,
  sessionStateMessageSchema,
  sessionStateSchema,
} from "./schemas/presence.js";
export {
  type AgentStatusReason,
  agentStatusReasonSchema,
  encodeProviderRetryEventMessage,
  PROVIDER_RETRY_EVENT_MESSAGE_PREFIX,
  type ProviderFailureCategory,
  type ProviderRetryEventName,
  type ProviderRetryEventPayload,
  type ProviderRetryScope,
  parseProviderRetryEventMessage,
  providerFailureCategorySchema,
  providerRetryEventNameSchema,
  providerRetryEventPayloadSchema,
  providerRetryScopeSchema,
  type ReplaySafety,
  replaySafetySchema,
  statusReasonFromProviderRetryEvent,
} from "./schemas/provider-retry.js";
export {
  type PulseBucket,
  type PulseTick,
  pulseBucketSchema,
  pulseTickSchema,
} from "./schemas/pulse.js";
export {
  AGENT_RESOURCE_BINDING_MODES,
  type AgentExtraRepoInput,
  type AgentResourceBindingInput,
  type AgentResourceBindingMode,
  type AgentResourcesOutput,
  type CreateTeamResource,
  canonicalizeResourceRepoUrl,
  createTeamResourceSchema,
  EFFECTIVE_RESOURCE_SOURCES,
  type EffectiveAgentResources,
  type EffectiveResourceRow,
  type EffectiveResourceSource,
  effectiveAgentResourcesSchema,
  effectiveResourceRowSchema,
  type NoSecretMcpServer,
  noSecretMcpServerSchema,
  type PromptResourcePayload,
  promptResourcePayloadSchema,
  RESOURCE_DEFAULT_ENABLED,
  RESOURCE_SCOPES,
  RESOURCE_STATUSES,
  RESOURCE_TYPES,
  type RepoResourcePayload,
  type ResourceDefaultEnabled,
  type ResourceImpactPreview,
  type ResourceImpactPreviewOutput,
  type ResourcePayload,
  type ResourceRow,
  type ResourceScope,
  type ResourceStatus,
  type ResourceType,
  type ResourceUsageOutput,
  repoResourcePayloadSchema,
  resourceImpactPreviewOutputSchema,
  resourceImpactPreviewSchema,
  resourcePayloadSchema,
  resourceRowSchema,
  resourceUsageOutputSchema,
  type SkillResourcePayload,
  skillResourcePayloadSchema,
  type UpdateAgentResources,
  type UpdateTeamResource,
  updateAgentResourcesSchema,
  updateTeamResourceSchema,
  validateEffectivePromptLength,
} from "./schemas/resource.js";
export {
  RUNTIME_AUTH_START_TYPE,
  type RuntimeAuthFailureReason,
  type RuntimeAuthLastError,
  type RuntimeAuthMethod,
  type RuntimeAuthProvider,
  type RuntimeAuthStartCommand,
  type RuntimeAuthStartRequest,
  type RuntimeAuthStartResponse,
  runtimeAuthFailureReasonSchema,
  runtimeAuthLastErrorSchema,
  runtimeAuthMethodSchema,
  runtimeAuthProviderSchema,
  runtimeAuthStartCommandSchema,
  runtimeAuthStartRequestSchema,
  runtimeAuthStartResponseSchema,
} from "./schemas/runtime-auth.js";
export {
  DEFAULT_RUNTIME_PROVIDER,
  DISABLED_RUNTIME_PROVIDERS,
  isRuntimeProviderEnabled,
  RUNTIME_PROVIDERS,
  type RuntimeProvider,
  runtimeProviderSchema,
} from "./schemas/runtime-provider.js";
export {
  type ScmAttentionLine,
  type ScmAttentionProvenance,
  type ScmAudienceEntry,
  type ScmLegacyRoute,
  scmAttentionLineSchema,
  scmAttentionProvenanceSchema,
  scmAudienceEntrySchema,
  scmLegacyRouteSchema,
} from "./schemas/scm-attention.js";
export {
  SCM_INGRESS_AUTHORITIES,
  SCM_PROVIDERS,
  type ScmIngressAuthority,
  type ScmIngressContext,
  type ScmProvider,
  type ScmSource,
  scmIngressAuthoritySchema,
  scmIngressContextSchema,
  scmProviderSchema,
  scmSourceSchema,
} from "./schemas/scm-source.js";
export {
  type AssistantTextEventPayload,
  assistantTextEventPayload,
  type ChatTokenUsage,
  type ContextTreeUsageEventPayload,
  chatTokenUsageSchema,
  contextTreeUsageEventPayload,
  type ErrorEventPayload,
  errorEventPayload,
  type SessionEvent,
  type SessionEventAcceptedFrame,
  type SessionEventKind,
  type SessionEventMessage,
  type SessionEventRejectedFrame,
  type SessionEventRejectedReason,
  type SessionEventRow,
  sessionEventAcceptedFrameSchema,
  sessionEventKind,
  sessionEventMessageSchema,
  sessionEventRejectedFrameSchema,
  sessionEventRejectedReasonSchema,
  sessionEventRowSchema,
  sessionEventSchema,
  type ThinkingEventPayload,
  type TokenUsageEventPayload,
  type ToolCallEventPayload,
  type ToolFileRef,
  type ToolFileRefOrigin,
  type ToolFileRefPathKind,
  type TurnEndEventPayload,
  thinkingEventPayload,
  tokenUsageEventPayload,
  toolCallEventPayload,
  toolFileRefOriginSchema,
  toolFileRefPathKindSchema,
  toolFileRefSchema,
  turnEndEventPayload,
} from "./schemas/session-event.js";
export {
  type SessionReconcileRequest,
  type SessionReconcileResult,
  sessionReconcileRequestSchema,
  sessionReconcileResultSchema,
} from "./schemas/session-reconcile.js";
export {
  type AgentSkills,
  agentSkillsSchema,
  SKILL_NAME_REGEX,
  SKILL_SOURCES,
  type SkillDescriptor,
  type SkillSource,
  skillDescriptorSchema,
  skillSourceSchema,
  type UpdateAgentSkills,
  updateAgentSkillsSchema,
} from "./schemas/skill.js";
export {
  type OrgStats,
  orgStatsSchema,
  type Stats,
  statsSchema,
} from "./schemas/stats.js";
export {
  type UsageAgentSummary,
  type UsageByAgentResponse,
  type UsageByAgentRow,
  type UsageDailyBucket,
  type UsageTurnRow,
  type UsageTurnsQuery,
  type UsageTurnsResponse,
  type UsageWindowQuery,
  usageAgentSummary,
  usageByAgentResponse,
  usageByAgentRow,
  usageDailyBucket,
  usageTurnRow,
  usageTurnsQuery,
  usageTurnsResponse,
  usageWindowQuery,
} from "./schemas/usage.js";
export {
  type CreateUser,
  createUserSchema,
  type UpdateUser,
  USER_STATUSES,
  type User,
  type UserStatus,
  updateUserSchema,
  userSchema,
  userStatusSchema,
} from "./schemas/user.js";
export {
  SOURCE_REPOS_DIRNAME,
  WORKSPACE_MANIFEST_FILENAME,
  WORKSPACE_STATE_DIRNAME,
  type WorkspaceManifest,
  workspaceManifestSchema,
} from "./schemas/workspace-manifest.js";
// -- WebSocket handshake frames --
export type {
  AuthControlFrame,
  AuthExpiredFrame,
  AuthRejectedCode,
  AuthRejectedFrame,
  AuthRetryableCode,
  AuthRetryableFrame,
  ServerCapabilities,
  ServerWelcomeFrame,
  WsAuthFrame,
} from "./schemas/ws-auth.js";
export {
  AUTH_REJECTED_CODES,
  AUTH_RETRYABLE_CODES,
  authControlFrameSchema,
  authExpiredFrameSchema,
  authRejectedCodeSchema,
  authRejectedFrameSchema,
  authRetryableCodeSchema,
  authRetryableFrameSchema,
  serverCapabilitiesSchema,
  serverWelcomeFrameSchema,
  WS_AUTH_FRAME_TIMEOUT_MS,
  wsAuthFrameSchema,
} from "./schemas/ws-auth.js";
export {
  classifyShellCommandIo,
  type ShellIoClassification,
  type ShellIoPathArg,
  type ShellIoPathKindHint,
  type ShellIoUnsupportedReason,
  stripShellCommandDisplayWrapper,
} from "./shell-command-io.js";
