// Core functions — programmatic API for external CLI consumers

// SDK — re-export for convenience
export type { AccessTokenProvider, RegisterResult, SdkConfig } from "@first-tree/client";
export { FirstTreeHubSDK, FirstTreeHubSDK as FirstTreeSDK, SdkError } from "@first-tree/client";
// Connect-token helpers — derive the server URL from a short code fallback or
// legacy JWT.
// `decodeJwtPayload` is intentionally NOT re-exported: it's an internal
// helper used by the CLI account-switch prompt, and its only legitimate
// public use case (URL derivation) already has a dedicated export.
export { deriveHubUrlFromToken, HubUrlDerivationError } from "./commands/_shared/connect-token.js";
// Core types
export type {
  ActivateContextTreeReadInput,
  CheckResult,
  ContextReviewConfigReader,
  ContextReviewConfigResult,
  ContextTreeBindingInput,
  ContextTreeConfigWriter,
  ContextTreeReadActivation,
  ContextTreeReadActivationErrorCode,
  ContextTreeReadAuthorityReader,
  ContextTreeReadGitRunner,
  ContextTreeReadSnapshotIdentity,
  ContextTreeReadStage,
  ContextTreeSeedAuthorityReader,
  ContextTreeSeedPreflight,
  ContextTreeSeedPreflightCliErrorCode,
  ContextTreeSeedStage,
  ContextTreeUpdateFailedCategory,
  ContextTreeWriteAuthorityReader,
  ContextTreeWritePreflight,
  ContextTreeWritePreflightCliErrorCode,
  ContextTreeWriteStage,
  MemberContextReviewConfigReader,
  MemberOrganizationProfile,
  MemberOrganizationResolutionCode,
  MigrationDetection,
  MigrationResult,
  PreflightContextTreeSeedInput,
  PreflightContextTreeWriteInput,
  RetireGithubScanResult,
  ServiceInfo,
  ServiceOpResult,
  ServiceState,
  SetContextTreeBindingOptions,
  WorkspaceBoundSource,
  WorkspaceStatus,
  WorkspaceUnboundSibling,
} from "./core/index.js";
export {
  AuthRefreshFailedError,
  AuthRefreshRateLimitedError,
  activateContextTreeRead,
  blank,
  ClientRuntime,
  ContextTreeReadActivationError,
  ContextTreeSeedPreflightCliError,
  ContextTreeUpdateFailedError,
  ContextTreeWritePreflightCliError,
  checkAgentConfigs,
  checkClientConfig,
  checkLegacyGithubScanRunner,
  checkNodeVersion,
  checkServerReachable,
  checkWebSocket,
  classifyContextTreeUpdateError,
  computeWorkspaceStatus,
  detectMigrationState,
  discoverWorkspaceRoot,
  ensureFreshAccessToken,
  ensureFreshAdminToken,
  formatCheckReport,
  getClientServiceStatus,
  handleClientOrgMismatch,
  InvalidContextTreeBindingInputError,
  InvalidContextTreeReadSnapshotError,
  installClientService,
  isInteractive,
  isServiceSupported,
  MemberOrganizationResolutionError,
  migrateWorkspaceToW1,
  onboardCheck,
  onboardCreate,
  pickImmediateWorkspaceSources,
  preflightContextTreeSeed,
  preflightContextTreeWrite,
  printResults,
  promoteToWorkspace,
  promptAddAgent,
  promptMissingFields,
  readContextReviewConfig,
  readContextTreeReadSnapshotIdentity,
  readMemberContextReviewConfig,
  readWorkspaceManifest,
  resolveAccessToken,
  resolveCliInvocation,
  resolveMemberOrganizationId,
  resolveServerUrl,
  restartClientService,
  retireLegacyGithubScanLaunchd,
  runLegacyGithubScanMigration,
  setAgentContextTreeBinding,
  slugFromFilename,
  startClientService,
  status,
  stopClientService,
  titleFromMarkdown,
  uninstallClientService,
  validateContextTreeBindingInput,
  writeWorkspaceManifest,
} from "./core/index.js";
